'use client';
import {useEffect,useState} from 'react';
import {createSupabaseClient,bearerHeaders} from '../../lib/supabase';
import {defaultSite} from '../../lib/editor-defaults';
type Item=Record<string,any>;
export default function VisualEditor(){
 const [data,setData]=useState<Item|null>(null),[selected,setSelected]=useState('site'),[draft,setDraft]=useState<Item>(defaultSite),[revision,setRevision]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading your editor…'),[query,setQuery]=useState(''),[section,setSection]=useState('Details'),[previewUrls,setPreviewUrls]=useState<Record<string,string>>({});
 async function api(path:string,options:RequestInit={}){const {data:{session}}=await createSupabaseClient().auth.getSession();if(!session)throw new Error('Log in to your owner account to open the editor.');const r=await fetch('/api/editor/'+path,{...options,headers:{...bearerHeaders(session.access_token),...options.headers}});const result:any=await r.json();if(!r.ok)throw new Error(result.error||'The editor could not complete this action.');return result;}
 async function load(){const result=await api('state');setData(result);return result;}
 function select(id:string,state:Item){const doc=state.documents.find((d:Item)=>d.id===id),p=state.products.find((p:Item)=>p.id===id);setSelected(id);setRevision(doc?.revision||0);setDraft(doc?.draft||(id==='site'?state.site:{...p,paidFile:p?.paidFile||'',coverFile:p?.coverFile||'',sampleFiles:p?.sampleFiles||[],relatedProducts:p?.relatedProducts||[],bundleProducts:p?.bundleProducts||[]}));setDirty(false);setSection('Details');setMessage('');}
 useEffect(()=>{load().then(d=>select('site',d)).catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,busy]);
 useEffect(()=>{let active=true;const urls:string[]=[];const ids=[draft.coverFile,...(draft.sampleFiles||[])].filter(Boolean);async function images(){const {data:{session}}=await createSupabaseClient().auth.getSession();if(!session)return;for(const id of ids){try{const r=await fetch('/api/editor/media?id='+encodeURIComponent(id),{headers:bearerHeaders(session.access_token)});if(r.ok){const url=URL.createObjectURL(await r.blob());urls.push(url);if(active)setPreviewUrls(v=>({...v,[id]:url}));}}catch{}}}images();return()=>{active=false;urls.forEach(URL.revokeObjectURL);};},[draft.coverFile,JSON.stringify(draft.sampleFiles)]);
 function change(k:string,v:any){setDraft(d=>({...d,[k]:v}));setDirty(true);setMessage('Unsaved changes');}
 function switchTo(id:string){if(busy)return;if(dirty&&!window.confirm('Leave without saving these changes?'))return;select(id,data!);}
 async function save(){const result=await api('save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected,revision,draft})});setRevision(result.revision);setDraft(result.draft);setDirty(false);await load();return result.revision;}
 async function action(publish=false){setBusy(true);try{const rev=dirty||revision===0?await save():revision;if(publish){await api('publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected,revision:rev})});await load();setMessage('Published. Your store now shows these changes.');}else setMessage('Draft saved privately. Your live store has not changed.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File|undefined,kind:string){if(!file)return;setBusy(true);setMessage('Uploading and checking '+file.name+'…');try{const f=await api(`upload?productId=${encodeURIComponent(selected)}&kind=${kind}&name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});setData(d=>({...d,files:[f,...(d?.files||[])]}));if(kind==='sample')change('sampleFiles',[...(draft.sampleFiles||[]),f.id]);else change(kind==='paid'?'paidFile':kind==='cover'?'coverFile':'samplerFile',f.id);setMessage('Upload complete. Save your draft, then publish when ready.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function downloadFile(id:string){setBusy(true);try{const {data:{session}}=await createSupabaseClient().auth.getSession();const r=await fetch('/api/editor/media?id='+encodeURIComponent(id),{headers:bearerHeaders(session?.access_token)});if(!r.ok)throw new Error('The file could not be opened.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=data?.files.find((f:Item)=>f.id===id)?.name||'resource';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const site=selected==='site',current=data?.products.find((p:Item)=>p.id===selected),doc=data?.documents.find((d:Item)=>d.id===selected);
 const isPublished=!dirty&&((revision>0&&doc?.published_revision===revision)||(revision===0&&!!current?.approved));
 const field=(label:string,key:string,multi=false)=> <label className="edit-field" key={key}>{label}{multi?<textarea value={draft[key]||''} rows={key==='description'||key==='heroText'?5:3} onChange={e=>change(key,e.target.value)}/>:<input value={draft[key]||''} onChange={e=>change(key,e.target.value)}/>}</label>;
 const list=(label:string,key:string)=> <label className="edit-field" key={key}>{label}<span className="edit-hint">One item per line</span><textarea rows={3} value={(draft[key]||[]).join('\n')} onChange={e=>change(key,e.target.value.split('\n'))}/></label>;
 const fileControl=(label:string,kind:string,accept:string,key:string)=> <div className="edit-upload"><strong>{label}</strong><p>{kind==='cover'||kind==='sample'?'PNG, JPG or WebP · maximum 8 MB':kind==='sampler'?'PDF · maximum 30 MB · available free after publishing':'PDF, PowerPoint or ZIP · maximum 30 MB · protected customer download'}</p><input aria-label={label} type="file" accept={accept} disabled={busy} onChange={e=>{upload(e.target.files?.[0],kind);e.target.value='';}}/>{(Array.isArray(draft[key])?draft[key]:draft[key]?[draft[key]]:[]).map((id:string)=><div className="edit-file" key={id}><span>{data?.files.find((f:Item)=>f.id===id)?.name||'Attached file'}</span><button type="button" onClick={()=>downloadFile(id)}>Open</button><button type="button" onClick={()=>change(key,Array.isArray(draft[key])?draft[key].filter((v:string)=>v!==id):'')}>Remove from draft</button></div>)}</div>;
 function newProduct(){if(busy)return;if(dirty&&!window.confirm('Leave without saving these changes?'))return;const id='resource-'+crypto.randomUUID().slice(0,8);setSelected(id);setDraft({title:'New learning resource',priceCents:500,approved:false,formats:['PDF'],included:[],pages:0,level:'',subject:'',description:'',source:'',sampleFiles:[],relatedProducts:[],bundleProducts:[]});setRevision(0);setDirty(true);setSection('Details');setMessage('New private product. Add its details and files before publishing.');}
 if(!data)return <main className="editor-login"><h1>Your visual editor</h1><p role="status">{message}</p><a href="/account">Log in to your store</a></main>;
 const entries=[...data.products,...data.documents.filter((d:Item)=>d.id!=='site'&&!data.products.some((p:Item)=>p.id===d.id)).map((d:Item)=>({id:d.id,...d.draft}))].filter((p:Item)=>(p.title+' '+p.id).toLowerCase().includes(query.toLowerCase()));
 const cover=draft.coverFile?previewUrls[draft.coverFile]:current?.thumbnailSrc||(!site&&current?'/product-thumbnails/'+selected+'.png?v=20260915b':'');
 return <main className="visual-editor"><header className="editor-top"><a href="/owner" className="editor-brand"><img src="/brand/saint-pierre-logo.png" alt=""/>Saint Pierre <span>Visual editor</span></a><div><a href="/" target="_blank" rel="noreferrer">View store ↗</a><a href="/owner">Orders & support</a></div></header><div className="editor-layout"><aside className="editor-sidebar"><button className={site?'selected':''} onClick={()=>switchTo('site')}>Homepage & navigation</button><div className="editor-list-heading"><h2>Catalog</h2><button onClick={newProduct}>+ New</button></div><input aria-label="Search catalog" placeholder="Find a resource…" value={query} onChange={e=>setQuery(e.target.value)}/><p>{entries.length} {entries.length===1?'resource':'resources'}</p><div className="editor-product-list">{entries.map((p:Item)=><button key={p.id} className={selected===p.id?'selected':''} onClick={()=>switchTo(p.id)}><strong>{p.title}</strong><small>{p.approved?'Published':'Private'}{data.documents.some((d:Item)=>d.id===p.id&&d.revision!==d.published_revision)?' · Draft saved':''}</small></button>)}</div></aside><section className="editor-work"><div className="editor-toolbar"><div><p>{site?'WEBSITE':'PRODUCT'}</p><h1>{site?'Homepage & store settings':draft.title}</h1><span>{dirty?'Unsaved changes':isPublished?'Published content':'Private draft'}</span></div><div><button disabled={busy} onClick={()=>action(false)}>Save draft</button><button className="editor-primary" disabled={busy} onClick={()=>action(true)}>{busy?'Working…':'Publish changes'}</button></div></div><p className="editor-status" role="status" aria-live="polite">{message||'Changes remain private until you publish.'}</p><div className="editor-tabs" aria-label="Editing sections">{(site?['Details','Navigation','Collections','Customer care','SEO']:['Details','Files & previews','Organization','SEO']).map(s=><button key={s} aria-pressed={section===s} className={s===section?'active':''} onClick={()=>setSection(s)}>{s}</button>)}</div><div className="editor-columns"><fieldset disabled={busy} className="editor-form"><legend className="sr-only">{section}</legend>
 {site&&section==='Details'&&<>{field('Headline','heroTitle')}{field('Second headline','heroAccent')}{field('Introduction','heroText',true)}{field('Button label','buttonLabel')}{field('Button destination','buttonUrl')}</>}
 {site&&section==='Navigation'&&<><p>Set the links in your homepage menu. Use website paths such as /#shop or /support.</p>{draft.navigation.map((n:Item,i:number)=><div className="edit-repeat" key={i}><label>Link text<input value={n.label} onChange={e=>change('navigation',draft.navigation.map((v:Item,j:number)=>j===i?{...v,label:e.target.value}:v))}/></label><label>Destination<input value={n.url} onChange={e=>change('navigation',draft.navigation.map((v:Item,j:number)=>j===i?{...v,url:e.target.value}:v))}/></label><button onClick={()=>change('navigation',draft.navigation.filter((_:Item,j:number)=>j!==i))}>Remove</button></div>)}<button onClick={()=>change('navigation',[...draft.navigation,{label:'New link',url:'/#shop'}])}>+ Add menu link</button></>}
 {site&&section==='Collections'&&<><p>Add collections to your homepage, then assign matching collection names under each product’s Organization tab. Your existing collections stay available.</p>{draft.collections.map((c:Item,i:number)=><div className="edit-repeat" key={i}><label>Collection name<input value={c.title} onChange={e=>change('collections',draft.collections.map((v:Item,j:number)=>j===i?{...v,title:e.target.value}:v))}/></label><label>Description<textarea value={c.description} onChange={e=>change('collections',draft.collections.map((v:Item,j:number)=>j===i?{...v,description:e.target.value}:v))}/></label><button onClick={()=>change('collections',draft.collections.filter((_:Item,j:number)=>j!==i))}>Remove</button></div>)}<button onClick={()=>change('collections',[...draft.collections,{title:'New collection',description:''}])}>+ Add collection</button></>}
 {site&&section==='Customer care'&&<>{field('Customer support message','supportText',true)}{field('Additional licensing information','licenseText',true)}<p>Your existing store policies remain available. Add clarifications here; review them before publishing.</p>{field('Free sampler title','samplerTitle')}{fileControl('Free sampler PDF','sampler','.pdf','samplerFile')}<a href="/owner">Manage customer messages and reviews →</a></>}
 {!site&&section==='Details'&&<>{field('Product title','title')}<div className="edit-two"><label className="edit-field">Price (USD)<input type="number" min="0.01" max="1000" step="0.01" value={draft.priceCents/100} onChange={e=>change('priceCents',Math.round(Number(e.target.value)*100))}/></label><label className="edit-field">Store visibility<select value={draft.approved?'sale':'private'} onChange={e=>change('approved',e.target.value==='sale')}><option value="private">Private / hidden</option><option value="sale">Listed for sale</option></select></label></div>{field('Description','description',true)}{field('Grade or course','level')}{field('Subject','subject')}{field('Standard or learning objective','standard',true)}{field('Resource type','resourceType')}{list('What’s included','included')}{list('File formats (PDF, PPTX, ZIP)','formats')}<label className="edit-field">Main page count<input type="number" min="0" value={draft.pages||0} onChange={e=>change('pages',Number(e.target.value))}/></label>{field('Lesson time','minutes')}{field('Answer key information','answerKey',true)}{field('Required book or materials','requiredBook',true)}{field('Product license','license',true)}{field('Detailed description','detailedDescription',true)}</>}
 {!site&&section==='Files & previews'&&<>{fileControl('Customer download','paid','.pdf,.pptx,.zip','paidFile')}{!draft.paidFile&&current?.ready&&<p>The existing verified customer download remains in place.</p>}{fileControl('Product cover','cover','.png,.jpg,.jpeg,.webp','coverFile')}{field('Cover description for accessibility','thumbnailAlt')}{fileControl('Sample page image','sample','.png,.jpg,.jpeg,.webp','sampleFiles')}{field('Preview description','previewDescription',true)}<p>Upload one complete ZIP when a product or bundle includes several files. Open it above and check every page before publishing.</p></>}
 {!site&&section==='Organization'&&<>{list('Collections','collections')}{list('Grade filters','grades')}{list('State filters','states')}{list('Search tags','tags')}<label className="edit-field">Related products<select multiple size={6} value={draft.relatedProducts||[]} onChange={e=>change('relatedProducts',Array.from(e.target.selectedOptions,o=>o.value))}>{data.products.filter((p:Item)=>p.id!==selected&&p.approved).map((p:Item)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="edit-field">Products included in this bundle<select multiple size={6} value={draft.bundleProducts||[]} onChange={e=>change('bundleProducts',Array.from(e.target.selectedOptions,o=>o.value))}>{data.products.filter((p:Item)=>p.id!==selected&&p.approved).map((p:Item)=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><p>Hold Command (Mac) or Ctrl (Windows) to select more than one. Bundle selections show included products; upload a complete ZIP under Files & previews to deliver them together.</p></>}
 {section==='SEO'&&<>{field('Search title','seoTitle')}{field('Search description','seoDescription',true)}<p>Search engines choose when to refresh published changes.</p></>}
 {doc?.previous&&<details className="editor-history"><summary>Previous published version</summary><p>Restore it as a draft, review it, then publish.</p><button onClick={()=>{setDraft(doc.previous);setDirty(true);setMessage('Previous version restored as an unsaved draft.');}}>Restore previous draft</button></details>}
 </fieldset><aside className="editor-preview"><div className="preview-caption">LIVE EDITING PREVIEW <span>{isPublished?'Published content':'Private preview'}</span></div>{site?<div className="editor-home-preview"><nav>{draft.navigation.map((n:Item,i:number)=><span key={i}>{n.label}</span>)}</nav><h2>{draft.heroTitle}<em>{draft.heroAccent}</em></h2><p>{draft.heroText}</p><span className="preview-cta">{draft.buttonLabel}</span>{draft.collections.map((c:Item,i:number)=><article key={i}><h3>{c.title}</h3><p>{c.description}</p></article>)}{draft.samplerTitle&&<p>Free sampler: {draft.samplerTitle}</p>}{draft.supportText&&<p>{draft.supportText}</p>}</div>:<article className="editor-card-preview">{cover?<img className="editor-cover" src={cover} alt={draft.thumbnailAlt||draft.title}/>:<div className="editor-empty-cover">Upload a product cover</div>}<div><p>{draft.subject} · {draft.level}</p><h2>{draft.title}</h2><p>{draft.description}</p><strong className="editor-price">{(draft.priceCents/100).toLocaleString('en-US',{style:'currency',currency:'USD'})}</strong><p>{draft.pages||0} pages · {(draft.formats||[]).join(' + ')}</p>{draft.requiredBook&&<p className="editor-book">{draft.requiredBook}</p>}<h3>What’s included</h3><ul>{(draft.included||[]).map((v:string,i:number)=><li key={i}>{v}</li>)}</ul>{(draft.sampleFiles||[]).map((id:string)=>previewUrls[id]&&<img key={id} src={previewUrls[id]} alt="Draft sample page"/>)}{!draft.sampleFiles?.length&&current?.previews?.[0]&&<img src={current.previews[0].src} alt="Current sample page"/>}</div></article>}<p className="edit-hint">This preview updates as you type. Check uploaded documents separately with Open.</p>{!site&&current?.approved&&<a href={'/products/'+selected} target="_blank" rel="noreferrer">View current published product ↗</a>}</aside></div></section></div></main>;
}
