import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{Miniflare}=createRequire(require.resolve('wrangler/package.json'))('miniflare'),{build}=createRequire(require.resolve('wrangler/package.json'))('esbuild');
await mkdir('.sites-runtime/editor-tests',{recursive:true});
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-05-15',d1Databases:['DB'],r2Buckets:['PAID_FILES']});
globalThis.__editorEnv={DB:await mf.getD1Database('DB'),PAID_FILES:await mf.getR2Bucket('PAID_FILES')};
const D=globalThis.__editorEnv.DB;
for(const sql of (await readFile('drizzle/0002_clumsy_warlock.sql','utf8')).split('--> statement-breakpoint'))await D.prepare(sql.trim()).run();
await build({entryPoints:['server/editor.ts','server/commerce.ts'],bundle:true,define:{'import.meta.env.VITE_STORE_PREVIEW':'"false"'},splitting:true,format:'esm',platform:'node',outdir:'.sites-runtime/editor-tests',outExtension:{'.js':'.mjs'},plugins:[{name:'isolated-bindings',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'fixture'}));b.onResolve({filter:/api\/_shared$/},()=>({path:'auth',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='env'?'export const env=globalThis.__editorEnv;':`export const isStoreOwner=u=>u?.userId==='owner';export async function signedIn(r){const id=r.headers.get('authorization');return id?{userId:id,email:'test@example.test'}:null;}`,loader:'js'}))}}]});
const e=await import('../.sites-runtime/editor-tests/editor.mjs'),s=await import('../.sites-runtime/editor-tests/commerce.mjs');await s.initialize();await D.prepare("UPDATE store_products SET ready=1 WHERE id='fl-grade5-theme'").run();
function req(input,who='owner'){return new Request('https://store.example/api/editor/save',{method:input?'POST':'GET',headers:{...(who?{authorization:who}:{}),'Content-Type':'application/json'},...(input?{body:JSON.stringify(input)}:{})});}
async function save(id,draft,revision=0){return (await e.editorSave(req({id,draft,revision}))).json();}
async function publish(id,revision){return e.editorPublish(req({id,revision}));}
const id='editor-test-product';
const draft={title:'Original teaching resource',description:'Complete original practice and answer guidance.',level:'Grade 7',subject:'Reading',priceCents:700,formats:['PDF'],included:['Practice','Answer key'],approved:false,pages:3};
async function upload(kind,name,bytes,productId=id){const r=new Request('https://store.example/api/editor/upload?productId='+productId+'&kind='+kind+'&name='+name,{method:'POST',headers:{authorization:'owner'},body:bytes});return(await e.editorUpload(r)).json();}
function media(id,who=''){return new Request('https://store.example/api/editor/media?id='+id,{headers:who?{authorization:who}:{}});}
after(()=>mf.dispose());
test('all authoring endpoints require the owner',async()=>{for(const who of ['', 'customer']){assert.equal((await s.safe(()=>e.editorGet(req(null,who)))).status,who?403:401);assert.equal((await s.safe(()=>e.editorSave(req({id,draft,revision:0},who)))).status,who?403:401);assert.equal((await s.safe(()=>e.editorPublish(req({id,revision:1},who)))).status,who?403:401);}});
test('draft survives reload and does not enter public catalog; stale edits are rejected',async()=>{await save(id,draft);const state=await(await e.editorGet(req())).json();assert.equal(state.documents.find(d=>d.id===id).draft.title,draft.title);assert.ok(!(await s.publicCatalog()).some(p=>p.id===id));assert.equal((await s.safe(()=>save(id,{...draft,title:'stale'},0))).status,409);});
test('unfinished products cannot be published for sale',async()=>{await save(id,{...draft,approved:true},1);assert.equal((await s.safe(()=>publish(id,2))).status,422);assert.equal(await D.prepare('SELECT id FROM store_products WHERE id=?').bind(id).first(),null);});
let paid,cover,sample;
test('uploads reject mismatched formats; private files require owner',async()=>{assert.equal((await s.safe(()=>upload('cover','fake.png','<script>bad</script>'))).status,422);paid=await upload('paid','resource.pdf','%PDF-1.7\nfixture');const png=await readFile('public/product-thumbnails/fl-grade5-theme.png');cover=await upload('cover','cover.png',png);sample=await upload('sample','sample.png',png);for(const f of [paid,cover,sample]){assert.equal((await s.safe(()=>e.editorMedia(media(f.id)))).status,401);assert.equal((await e.editorMedia(media(f.id,'owner'))).status,200);}});
test('publishing commits a complete product, images become public and paid file stays private',async()=>{const r=await save(id,{...draft,approved:true,paidFile:paid.id,coverFile:cover.id,sampleFiles:[sample.id]},2);await publish(id,r.revision);const p=(await s.publicCatalog()).find(p=>p.id===id);assert.equal(p.priceCents,700);assert.equal(p.ready,true);assert.equal(p.thumbnailSrc,'/api/editor/media?id='+cover.id);assert.equal((await e.editorMedia(media(cover.id))).status,200);assert.equal((await s.safe(()=>e.editorMedia(media(paid.id)))).status,401);assert.equal((await s.safe(()=>s.downloadToken(req({productId:id},'customer')))).status,403);});
test('later drafts cannot alter live prices; publishing retains previous version',async()=>{const r=await save(id,{...draft,priceCents:900,approved:true,paidFile:paid.id,coverFile:cover.id,sampleFiles:[sample.id]},3);assert.equal((await s.publicCatalog()).find(p=>p.id===id).priceCents,700);assert.equal((await s.safe(()=>publish(id,3))).status,409);await publish(id,r.revision);assert.equal((await D.prepare('SELECT price_cents FROM store_products WHERE id=?').bind(id).first()).price_cents,900);const doc=await D.prepare('SELECT previous FROM editor_documents WHERE id=?').bind(id).first();assert.equal(JSON.parse(doc.previous).priceCents,700);});
test('existing resources preserve rich metadata and respect owner edits over static content',async()=>{const state=await(await e.editorGet(req())).json(),p=state.products.find(p=>p.id==='fl-grade5-theme');await save(p.id,{...p,title:'Updated title',description:'Owner revised description',priceCents:825});await publish(p.id,1);const revised=(await s.publicCatalog()).find(x=>x.id===p.id);assert.equal(revised.title,'Updated title');assert.equal(revised.description,'Owner revised description');assert.equal(revised.priceCents,825);assert.ok(revised.collections.length>0);assert.ok(revised.grades.length>0);assert.ok(revised.states.includes('Florida'));});
test('homepage drafts stay private, unsafe links and foreign-origin writes fail',async()=>{const current=await e.siteContent();await save('site',{...current,heroTitle:'New headline'});assert.equal((await e.siteContent()).heroTitle,current.heroTitle);await publish('site',1);assert.equal((await e.siteContent()).heroTitle,'New headline');assert.equal((await s.safe(()=>save('site',{...current,buttonUrl:'javascript:alert(1)'},1))).status,422);const r=req({id,draft,revision:4});r.headers.set('origin','https://foreign.example');assert.equal((await s.safe(()=>e.editorSave(r))).status,403);});
test('unpublishing removes catalog entry without deleting its stored files',async()=>{await save(id,{...draft,approved:false,paidFile:paid.id,coverFile:cover.id,sampleFiles:[sample.id]},4);await publish(id,5);assert.ok(!(await s.publicCatalog()).some(p=>p.id===id));assert.equal((await s.safe(()=>e.editorMedia(media(cover.id)))).status,401);assert.equal((await e.editorMedia(media(paid.id,'owner'))).status,200);});

test('catalog initialization preserves editor-uploaded files and prices on release products',async()=>{const productId='nc-g3-equal-groups-teaching-bundle';const state=await(await e.editorGet(req())).json();const current=state.products.find(p=>p.id===productId);const replacement=await upload('paid','replacement.pdf','%PDF-1.7\nreplacement',productId);await save(productId,{...current,priceCents:1375,paidFile:replacement.id});await publish(productId,1);await s.initialize();const row=await D.prepare('SELECT price_cents,storage_key,metadata FROM store_products WHERE id=?').bind(productId).first();assert.equal(row.price_cents,1375);assert.ok(row.storage_key.startsWith('editor/'));assert.equal(JSON.parse(row.metadata).editorManaged,true);});
