"""Original Grade 8 NC ELA reading-standard packets (RL.8.x and RI.8.x).

Same format as rl_ri_grade7_content.py: original passages written for a more
mature (8th-grade) reading level, plus a 20-item Q&A bank per standard with
reasoning in every answer. No released-test or third-party material is used.
Standard codes and text are the Common Core Reading Literature / Reading
Informational Text standards for grade 8, which North Carolina's Standard
Course of Study adopts under the same numbering.
"""
NC = 'https://www.thecorestandards.org/ELA-Literacy/'
ROWS = []


def add(slug, title, code, standard_text, objective, lesson, models, texts, items, price):
    assert len(items) == 20, (slug, len(items))
    assert len(models) == 2
    assert len(texts) in (1, 2), (slug, len(texts))
    strand = 'RL' if code.startswith('RL') else 'RI'
    num = code.split('.')[-1]
    ROWS.append(dict(id='nc-g8-' + slug, title=title, state='North Carolina', grade='8', subject='Reading',
        standard=code + ' — ' + standard_text, objective=objective,
        source=NC + strand + '/8/' + num + '/', resourceType='Complete ELA practice packet',
        lesson=lesson, models=models, texts=texts,
        items=[{'q': q, 'answer': a, 'work': a} for q, a in items], price=price))


# ---------------------------------------------------------------- RL.8.1
add('rl81-textual-evidence', 'Evidence and Inference Lab', 'RL.8.1',
 'Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.',
 'Cite the textual evidence that most strongly supports an analysis of explicit statements and inferences drawn from a literary text.',
 'Explicit evidence is stated directly in the text; an inference is a reasonable conclusion built from evidence plus what a reader already knows. At grade 8, "most strongly supports" means choosing the single best piece of evidence, not just any evidence that fits — weigh competing details and explain why one supports the analysis better than another.',
 [('Paragraph 2 says Marcus "read the acceptance letter four times, then folded it into his back pocket instead of showing anyone." What is the strongest evidence for an inference that he is unsure how to feel about the news?',
   'The detail that he read it four times but told no one is the strongest evidence — rereading suggests he is still processing the news, and folding it away instead of sharing it suggests he is not ready to react publicly, which together support uncertainty rather than simple excitement or disappointment.'),
  ('Between "the gym was hot" and "she wiped her palms on her shorts three times before the serve," which detail more strongly supports an inference about nervousness, and why?',
   'The second detail more strongly supports nervousness because it is a specific, repeated physical action tied directly to the moment of pressure, while "the gym was hot" is a general environmental fact that could support many different inferences.')],
 [('The Acceptance Letter', (
   '1. Marcus had applied to the magnet arts high school without telling his older brother, Dante, who had been rejected from the same program two years earlier and had not mentioned it since. Marcus kept his own application folded inside a library book so it would not turn up in a drawer.\n\n'
   '2. The letter came on a Tuesday, while Dante was at practice. Marcus read the acceptance letter four times, then folded it into his back pocket instead of showing anyone. He went to his room and closed the door, which he almost never did.\n\n'
   '3. At dinner, their mother asked if anything interesting had happened that day. Marcus said no. Dante, half-listening, asked to be passed the rice. Marcus passed it and said nothing else for the rest of the meal.\n\n'
   '4. Over the next week, Marcus carried the letter with him — to school, to the bus stop, once even into the shower, where it sat on the sink until he remembered and moved it. He did not read it again. He also did not throw it away.\n\n'
   '5. On Saturday, Dante found him in the garage, sitting on an overturned bucket, the letter open on his knee. "You\'ve had that a week," Dante said. It was not a question. Marcus had not heard him come in.\n\n'
   '6. "I didn\'t want it to be a thing," Marcus said. "You didn\'t get in, and I—" He stopped. Dante sat down on a second bucket, close enough that their shoulders nearly touched.\n\n'
   '7. "I got in your way for two years without meaning to," Dante said. "Read it out loud. I want to hear how it sounds when it\'s actually happening to someone." Marcus looked at him for a long moment before he understood that Dante meant it.\n\n'
   '8. Marcus read the letter aloud, once, in the garage, with the door up and the evening light coming in sideways across the concrete. When he finished, Dante didn\'t say anything about his own rejection at all. He just said, "You should tell Mom tonight," and meant it kindly.\n\n'
   '9. That night at dinner, Marcus told her. Dante, across the table, was the first to smile.'))],
 [('What does paragraph 1 state explicitly about how Marcus applied to the magnet school?', 'He applied without telling Dante, and kept the application folded inside a library book so it would not be found.'),
  ('What is the strongest evidence that Marcus is anxious about how Dante will react to the news? Cite it and explain why it is the strongest choice.', 'The strongest evidence is that he hid the application inside a library book (paragraph 1) and later hid the acceptance letter in his pocket instead of telling anyone (paragraph 2); these two deliberate acts of concealment, both aimed at avoiding Dante finding out, more strongly support anxiety than a single detail like closing his door would alone.'),
  ('What explicit action does Marcus take with the letter in paragraph 2?', 'He reads it four times, then folds it into his back pocket instead of showing anyone, and closes his bedroom door.'),
  ('Which detail from paragraph 3 most strongly supports an inference that Marcus is deliberately hiding something at dinner, and why is it stronger than the fact that he "said no"?', '"Marcus... said nothing else for the rest of the meal" is stronger, because staying unusually silent for an entire meal is a sustained behavior change, while a single "no" answer alone could simply mean nothing happened that day.'),
  ('What explicit detail in paragraph 4 shows Marcus cannot decide what to do with the letter?', 'He carries it everywhere for a week, including into the shower, but does not read it again and does not throw it away.'),
  ('What can you infer about why Marcus does not throw the letter away, even though he also will not talk about it? Cite the strongest evidence.', 'He likely still wants to keep the acceptance real to himself even while afraid to share it; the strongest evidence is that he carries it everywhere, including into the shower (paragraph 4), which shows the letter matters enough to stay physically close even without being discussed.'),
  ('What explicit statement in paragraph 5 shows Dante already suspected something?', '"You\'ve had that a week," Dante said — stated as fact, not a question, showing he already knew or had guessed.'),
  ('Between "It was not a question" and "Marcus had not heard him come in," which more strongly supports the inference that Dante had been quietly paying attention to Marcus all week? Explain.', '"It was not a question" more strongly supports it, because it shows Dante already had enough information to state a fact rather than ask, which requires him to have been observing Marcus over time, while "Marcus had not heard him come in" only shows Marcus was distracted in that moment.'),
  ('What explicit reason does Marcus give in paragraph 6 for hiding the letter?', 'He says he "didn\'t want it to be a thing," and starts to reference Dante not getting in before stopping himself.'),
  ('What can you infer about Dante\'s feelings toward his own rejection from paragraph 7? Cite the strongest evidence.', 'He seems to have made peace with it or wants to face it directly rather than avoid it; the strongest evidence is his direct request, "Read it out loud. I want to hear how it sounds when it\'s actually happening to someone," which shows he is choosing to engage with the painful topic rather than avoid it.'),
  ('What explicit physical detail in paragraph 7 shows a shift toward closeness between the brothers?', 'Dante sits down on a second bucket, close enough that their shoulders nearly touch.'),
  ('Which is the stronger evidence that Dante has genuinely moved past resentment: sitting close to Marcus, or asking him to read the letter aloud? Explain your reasoning.', 'Asking Marcus to read the letter aloud is stronger evidence, because it is an active choice to face the source of possible resentment directly, while sitting close is a smaller, more passive gesture that could occur without resolving deeper feelings.'),
  ('What explicit detail describes the setting as Marcus reads the letter aloud in paragraph 8?', 'The garage door is up and the evening light is coming in sideways across the concrete.'),
  ('What can you infer from Dante saying nothing about his own rejection after Marcus finishes reading? Cite evidence.', 'It suggests Dante is intentionally keeping the moment focused on Marcus rather than making it about himself; paragraph 8 states he "didn\'t say anything about his own rejection at all" immediately after the reading, which is a deliberate omission given the topic\'s relevance.'),
  ('What explicit words does Dante use to encourage Marcus at the end of paragraph 8?', '"You should tell Mom tonight."'),
  ('What is the strongest evidence in the whole story that Dante\'s support is sincere rather than reluctant? Justify your choice.', 'The strongest evidence is that Dante is "the first to smile" when Marcus tells their mother (paragraph 9); a genuine, immediate positive reaction at the emotional climax carries more weight than his earlier words alone, since actions in the story\'s final moment confirm what his words suggested.'),
  ('Explain the difference between explicit and inferred information using two examples from this story.', 'Explicit: the text directly states Marcus read the letter four times (paragraph 2). Inferred: the reader must conclude from his silence and hiding behavior that he feels anxious or unsure, since the story never states his emotions directly.'),
  ('A classmate claims the story is only about sibling rivalry. Using the strongest textual evidence, explain why that analysis is incomplete.', 'The story is more about reconciliation than rivalry; the strongest evidence against a rivalry-only reading is Dante\'s statement, "I got in your way for two years without meaning to" (paragraph 7), which shows him taking responsibility and moving toward connection rather than continuing to compete.'),
  ('Identify one place in the story where two different inferences could reasonably be drawn from the same evidence, and explain both.', 'Dante finding Marcus in the garage (paragraph 5) could support either "Dante has been quietly worried about Marcus" or "Dante happened to walk in by chance"; the story leans toward the first because Dante already knows how long Marcus has had the letter, which is unlikely to be coincidence.'),
  ('Write one full inference about Dante, and identify the single strongest piece of evidence that supports it, explaining why it beats at least one other possible piece of evidence.', 'Answers vary; require a clear inference about Dante plus one specific cited detail, with an explanation of why that detail supports the inference more strongly than another available detail.')],
 600)

# ---------------------------------------------------------------- RI.8.1
add('ri81-evidence-informational', 'Strongest Evidence Workshop', 'RI.8.1',
 'Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.',
 'Cite the textual evidence that most strongly supports an analysis of explicit statements and inferences drawn from an informational text.',
 'In informational text, explicit evidence often appears as stated facts, data, or direct quotations from sources. An inference in informational text is a reasonable conclusion drawn from combining facts, not a claim the text states outright. At grade 8, choosing the "strongest" evidence means comparing multiple possible pieces of support and explaining why one is more precise, more directly relevant, or more reliable than another.',
 [('A report states "the bridge was inspected in 2019" and separately "engineers recommended repairs in March 2024 after finding corrosion in support cables." Which detail more strongly supports an inference that the bridge\'s condition worsened over time, and why?',
   'The second detail is stronger, because it directly identifies a specific problem (corrosion) and a specific recommendation for repair, while the first detail alone only establishes a date and says nothing about the bridge\'s condition.'),
  ('If a text states a company\'s profits and separately quotes an employee saying morale was low, which is stronger evidence for an inference about employee experience, and why?',
   'The employee quote is stronger for an inference specifically about employee experience, because it comes from a direct source describing that experience, while profit figures describe financial results and only indirectly relate to how employees felt.')],
 [('Second Chances: How One City Rebuilt Its Public Library System (Part 1)', (
   '1. In 2015, the city of Millbrook faced a decision: renovate its aging central library or close two of its three branches to cut costs. The central library, built in 1962, had not been substantially updated in over fifty years. Its roof leaked in four places, and its basement archive had flooded twice in the previous decade.\n\n'
   '2. City council member Rosa Ibarra argued against closures. "A library is not a luxury," she told the council in a recorded session. "For some families, it is the only place with reliable internet, air conditioning in summer, and a quiet room to study." Her statement was backed by a city survey showing that 38 percent of library visitors used the building for internet access alone.\n\n'
   '3. Opponents of renovation pointed to cost. Estimates from the city engineer placed the renovation at $4.2 million, compared to an estimated $600,000 in annual savings from closing two branches. At that rate, opponents argued, renovation would take seven years just to break even.\n\n'
   '4. The council commissioned an independent study in 2016. The study found that library usage had actually increased by 22 percent over the previous five years, driven largely by after-school programs and job-search workshops for adults. It also found that the two branches proposed for closure served neighborhoods with the city\'s lowest average household income.')),
  ('Second Chances: How One City Rebuilt Its Public Library System (Part 2)', (
   '5. In 2017, the council voted 5–2 to renovate rather than close branches, funding the project through a mix of municipal bonds and a state library-improvement grant. Construction began in 2018 and was completed in early 2020, just before a period when library usage nationally would shift significantly due to public health measures.\n\n'
   '6. By 2023, three years after renovation, Millbrook\'s library system reported that overall visits across all three branches had risen 41 percent compared to 2015 levels. The after-school program alone served over 900 students that year, more than triple its 2015 enrollment of 280.\n\n'
   '7. Rosa Ibarra, no longer on the council but still a frequent visitor, was asked in a 2023 newspaper interview whether the investment had been worth it. She pointed not to the usage statistics but to a single detail: the renovated building now had four public meeting rooms, all booked solid most weeknights, used by tutoring groups, citizenship-class students, and a monthly repair café where residents fixed broken appliances instead of throwing them away.'))],
 [('What does paragraph 1 state explicitly about the library\'s physical condition before renovation?', 'The roof leaked in four places, and the basement archive had flooded twice in the previous decade.'),
  ('Which piece of evidence most strongly supports the inference that low-income families would be most affected by branch closures, and why is it stronger than other available evidence?', 'The finding in paragraph 4 that the branches proposed for closure served neighborhoods with the city\'s lowest average household income is strongest, because it directly and specifically connects closure to income level, unlike Rosa Ibarra\'s general statement about libraries being important, which does not specify which neighborhoods would be affected.'),
  ('What explicit statistic does the city survey provide about internet access, according to paragraph 2?', '38 percent of library visitors used the building for internet access alone.'),
  ('What is the strongest evidence for an inference that renovation opponents were focused mainly on short-term cost rather than long-term community impact? Explain your choice.', 'The strongest evidence is that opponents calculated renovation would "take seven years just to break even" (paragraph 3), a purely financial comparison; this is stronger than simply noting they opposed renovation, because it shows their argument was built specifically around a break-even cost calculation rather than community outcomes.'),
  ('What explicit finding did the 2016 independent study report about library usage trends?', 'Library usage had increased by 22 percent over the previous five years.'),
  ('Between the 22 percent usage increase and the finding about low-income neighborhoods, which more strongly supports the council\'s eventual decision to renovate rather than close branches? Justify your answer.', 'The finding about low-income neighborhoods is somewhat stronger for justifying renovation specifically over closure, because it identifies a direct equity consequence of closing branches, while the usage increase shows the library was valuable but does not by itself argue against closing the two lower-use branches.'),
  ('What explicit vote result is stated in paragraph 5?', 'The council voted 5–2 to renovate rather than close branches.'),
  ('What can you infer about the timing of the renovation\'s completion from paragraph 5? Cite the strongest evidence.', 'The renovation was completed at a fortunate time, just before increased public reliance on libraries; the strongest evidence is the phrase "just before a period when library usage nationally would shift significantly due to public health measures," which directly signals a timing connection without stating the outcome explicitly.'),
  ('What explicit statistic does paragraph 6 give about overall visit growth by 2023?', 'Overall visits across all three branches had risen 41 percent compared to 2015 levels.'),
  ('Which is stronger evidence that the after-school program specifically drove the increase in usage: the 22 percent five-year increase from 2016, or the tripling of after-school enrollment mentioned in paragraph 6? Explain.', 'The tripling of after-school enrollment (from 280 to over 900 students) is stronger, because it isolates one specific program\'s growth, while the 22 percent figure is a broader usage statistic that could be caused by many different factors, not just after-school programs.'),
  ('What explicit detail does Rosa Ibarra point to in paragraph 7 when asked if the investment was worth it?', 'The four public meeting rooms, booked solid most weeknights with tutoring groups, citizenship-class students, and a repair café.'),
  ('Why might Rosa Ibarra\'s choice to cite meeting-room usage, rather than the 41 percent visit increase, be considered strong evidence of her personal view? Explain using the text.', 'It suggests she values the library\'s role as a community gathering space more than raw visitor numbers; the text explicitly says she "pointed not to the usage statistics but to" the meeting rooms, showing a deliberate choice to emphasize a different kind of evidence than the official statistics.'),
  ('Explain the difference between an explicit fact and an inference using two examples from this article.', 'Explicit: the article directly states the renovation cost $4.2 million (paragraph 3). Inference: a reader must conclude that community programs, not just building repairs, drove the growth in usage, since the article never states this as a single direct claim but supports it with several related facts.'),
  ('A reader claims the article proves renovation was purely a financial success. Using the strongest evidence, explain why this claim oversimplifies the article.', 'The claim oversimplifies the article because the strongest evidence of impact, such as the growth in after-school enrollment and the daily use of meeting rooms, describes community and educational outcomes, not financial ones; the article never presents a direct financial return figure to support a claim of purely financial success.'),
  ('Which piece of evidence in the article is least useful for supporting an inference about community impact, and why?', 'The $4.2 million renovation estimate (paragraph 3) is least useful for that specific inference, because it is a cost figure that describes the investment itself rather than any outcome or effect on the community.'),
  ('Identify one place in the article where two different inferences could reasonably be drawn from the same evidence, and explain both.', 'The 5–2 council vote (paragraph 5) could support either "most council members were convinced by the equity findings" or "two members had unresolved concerns about cost"; both are reasonable, since the article states the vote but does not explain the two dissenting votes.'),
  ('What explicit detail from paragraph 4 identifies which programs drove the usage increase, and why is it stronger evidence than simply citing the 22 percent figure alone?', 'The article explicitly states the increase was "driven largely by after-school programs and job-search workshops for adults"; naming the specific programs is stronger evidence than the 22 percent figure alone, because it explains the cause of the growth rather than just reporting that growth happened.'),
  ('Why does the article include the detail that construction finished "just before" a period of national change in library use? What inference does this support?', 'It supports the inference that Millbrook\'s renovation was fortunately timed, which strengthens the case that the investment paid off, since the newly renovated building was ready right as broader demand for library services likely shifted.'),
  ('Compare the strength of Rosa Ibarra\'s 2015 survey statistic (paragraph 2) to the 2023 enrollment statistic (paragraph 6) as evidence for the renovation\'s long-term success. Which is stronger, and why?', 'The 2023 enrollment statistic is stronger evidence of long-term success, because it measures an actual outcome years after renovation was completed, while the 2015 survey statistic only measured need before the renovation happened and cannot by itself confirm the investment worked.'),
  ('Write one full inference about the value of the renovation to the community, and identify the single strongest piece of evidence that supports it, explaining why it beats at least one other candidate detail.', 'Answers vary; require a clear inference plus one specific cited detail, with an explanation of why that detail supports the inference more strongly than at least one other available detail from the article.')],
 600)

# ---------------------------------------------------------------- RL.8.2
add('rl82-theme-central-idea', 'Theme Through the Wreckage', 'RL.8.2',
 'Determine a theme or central idea of a text and analyze its development over the course of the text, including its relationship to the characters, setting, and plot; provide an objective summary of the text.',
 'Determine a theme of a literary text, analyze how it develops through its relationship to characters, setting, and plot, and write an objective summary.',
 'A theme is a message about life, stated as a full sentence, not a one-word topic. At grade 8, tracing a theme means showing its relationship to specific story elements: how a character\'s choices, the setting\'s pressures, and plot turns work together to develop it, not just naming a lesson at the end. An objective summary reports events in order without opinions or added judgment.',
 [('Topic: teamwork under pressure. Write a possible theme as a full sentence, and name one story element (character, setting, or plot) that might develop it.',
   'A possible theme: "Real teamwork means adapting the plan together, not defending your own idea." The plot — a sudden setback that forces the team to change course together — is the element most likely to develop this theme.'),
  ('Which sentence is an objective summary sentence, and which is an opinion: (a) "The robot\'s arm jammed during the final test," (b) "The team foolishly ignored the obvious wiring problem"?',
   'Sentence (a) is objective — it reports a fact without judgment. Sentence (b) is an opinion, because "foolishly" and "obvious" are the writer\'s judgments, not neutral facts.')],
 [('The Circuit Breaks (Part 1)', (
   '1. Priya had wired the claw mechanism four times, and four times it had worked in the practice garage. Two hours before the regional competition, it worked a fifth time, lifting a foam block cleanly onto the scoring platform while her teammates Malik and Deja cheered from across the room.\n\n'
   '2. Forty minutes before their first match, the claw stopped closing. Priya popped the access panel and found a wire scorched black where it should have been copper-bright. "Bad connector," she said. "I can rewire it, but not in forty minutes. Not alone."\n\n'
   '3. Malik wanted to swap in the backup claw design they had scrapped three weeks earlier for being too slow. Deja wanted to skip the claw task entirely and focus the match on driving points instead, which the robot could still score without a working arm. Priya wanted to keep rewiring and hope.\n\n'
   '4. They had six minutes left to decide when their coach, Mr. Ferris, said only, "Whatever you pick, pick it together, not three separate robots in one shell." He did not tell them which to choose.')),
  ('The Circuit Breaks (Part 2)', (
   '5. Priya put down her wire strippers. "The backup claw is slower, but it\'s reliable, and Deja\'s driving points still count if the claw fails mid-match anyway. We don\'t have to choose one plan. We can run the backup claw as backup, exactly like its name says, and lean on driving if it still doesn\'t work."\n\n'
   '6. Malik reinstalled the backup arm in under four minutes while Deja recalibrated the drive code for scoring without relying on any claw at all. Priya, instead of finishing her rewire, called out timing cues to both of them so their work would not collide inside the crowded chassis.\n\n'
   '7. The backup claw was slow, exactly as Malik had warned. In their first match, it lifted only one block, fumbling a second. But Deja\'s driving scored steadily the whole match, and when the claw did fumble, no one on the team stopped to blame it, because the whole plan had been built to survive that fumble.\n\n'
   '8. They did not win the regional. They placed ninth of twenty-two, high enough to be invited to the state qualifier. At the drive-home meeting, Priya still wanted to know why the connector had scorched. Malik wanted to redesign the claw entirely. Deja wanted to keep the driving code exactly as it was.\n\n'
   '9. "Three different repair lists," Mr. Ferris said, almost smiling, "and one robot that made it to state because none of you tried to run it alone at minute forty."'))],
 [('What explicit detail in paragraph 1 shows the claw mechanism had worked reliably before the competition?', 'It had worked five times total in testing, including once two hours before the competition, lifting a foam block cleanly.'),
  ('What is the topic of this story in a few words, and how is that different from a theme?', 'The topic is teamwork or robotics competition; a topic is just a subject, while a theme must be a full-sentence message about life that the story teaches through its events.'),
  ('What explicit problem does Priya find in paragraph 2, and how much time is left to fix it?', 'A wire is scorched black where it should be copper-bright, a bad connector, with about forty minutes left before the first match.'),
  ('How do the three teammates\' different proposals in paragraph 3 reflect their individual characters?', 'Priya wants to keep fixing her own work (persistence with her original plan), Malik wants to fall back on a known design (caution), and Deja wants to change strategy entirely (adaptability) — each proposal reflects a different way of responding to pressure.'),
  ('What does Mr. Ferris\'s statement in paragraph 4 suggest about the theme the story is building toward?', 'It suggests the theme will involve the difference between individual effort and true collaboration — he does not solve the problem for them, but insists the solution be a shared one.'),
  ('How does the setting (a competition with a hard time limit) shape the plot decision in paragraph 3?', 'The ticking clock removes the option of debating endlessly or trying all three ideas in sequence; the pressure of limited time forces the team to combine ideas quickly rather than pick just one.'),
  ('What plan does Priya propose in paragraph 5, and how does it differ from simply picking one teammate\'s idea?', 'She proposes combining the backup claw with Deja\'s driving-focused strategy as a safety net for each other, rather than choosing only Malik\'s idea or only Deja\'s idea alone.'),
  ('How does Priya\'s action in paragraph 6 (calling out timing cues instead of finishing her own rewire) show character development from paragraph 2?', 'In paragraph 2 she wanted to keep working on her own fix alone; by paragraph 6 she sets aside her individual task to support both teammates\' work, showing a shift toward collaboration.'),
  ('What explicit outcome does the backup claw have during the first match, according to paragraph 7?', 'It lifts only one block and fumbles a second one, performing slowly as expected.'),
  ('How does the team\'s reaction to the claw\'s fumble in paragraph 7 develop the story\'s theme?', 'No one blames the claw or each other for the fumble, because the plan was deliberately built to survive that kind of failure — this shows the theme that shared planning protects a team from a single point of failure.'),
  ('What explicit competition result is stated in paragraph 8?', 'They placed ninth of twenty-two teams, which was high enough to qualify for the state competition.'),
  ('How does paragraph 8 complicate a simple "teamwork always agrees" reading of the theme? Use evidence.', 'The team still disagrees afterward — Priya wants to investigate the connector, Malik wants to redesign the claw, and Deja wants to keep her code unchanged — showing the theme is not about eliminating disagreement, but about not acting on it alone under pressure.'),
  ('What does Mr. Ferris\'s final line in paragraph 9 suggest is the real reason the team succeeded?', 'It suggests they succeeded because they combined their different ideas into one shared plan at the critical moment, rather than because any one of their individual ideas was correct.'),
  ('State a theme for this story as a complete sentence, using a story element to support it.', 'Answers vary; must be a full-sentence life lesson, such as "A team survives a crisis by combining differing ideas rather than any one person acting alone," supported by referencing the plot moment when Priya combines the three proposals.'),
  ('Write one objective sentence summarizing paragraphs 1–2 (no opinions).', 'Priya\'s claw mechanism had worked reliably in testing, but forty minutes before their first match, she discovered a scorched connector had caused it to stop working.'),
  ('Identify one word in this draft summary that is an opinion, not a fact: "Priya bravely sacrificed her own fix to help her panicking teammates."', '"Bravely" and "panicking" are opinions/judgments about the characters\' emotional states and actions, not neutral facts stated in the text.'),
  ('Write an objective one-sentence summary of the story\'s ending (paragraphs 8–9).', 'The team placed ninth of twenty-two and qualified for the state competition, and their coach noted that combining their different ideas, rather than acting alone, was what got them there.'),
  ('Why is "the team\'s only good idea was Priya\'s combined plan" not appropriate for an objective summary?', 'It is an opinion and an overstatement; the text shows all three ideas contributed to the final plan, so crediting only Priya misrepresents what the story actually states.'),
  ('Combine paragraphs 5, 6, and 7 into one two-sentence objective summary.', 'Priya proposed combining the backup claw with Deja\'s driving-focused strategy, and Malik and Priya worked together to install and coordinate it in the remaining minutes. The backup claw performed slowly and fumbled once during the match, but the team\'s driving points kept them competitive.'),
  ('Trace how the theme develops from the team\'s disagreement in paragraph 3 to their shared success in paragraph 7, citing at least two moments.', 'In paragraph 3, the three teammates each push a separate plan; by paragraph 6, Priya sets aside her own repair to support the combined plan, and in paragraph 7, the team does not blame the claw\'s fumble because the plan was built to withstand it — together these moments trace a shift from separate individual plans to one shared, resilient plan.')],
 600)

# ---------------------------------------------------------------- RI.8.2
add('ri82-central-ideas-summary', 'Tracing the Central Idea', 'RI.8.2',
 'Determine a central idea of a text and analyze its development over the course of the text, including its relationship to supporting ideas; provide an objective summary of the text.',
 'Determine a central idea of an informational text, analyze how supporting ideas develop it across the text, and write an objective summary.',
 'A central idea is the main point an informational text develops, not just its topic. Supporting ideas are the smaller points, facts, or examples that build and refine the central idea as the text progresses. At grade 8, tracing development means showing how specific supporting ideas connect to and strengthen the central idea from one part of the text to another, not just restating the topic.',
 [('Topic: a city\'s new recycling program. Write a possible central idea as a full sentence, and name one type of supporting idea (a fact, statistic, or example) that might develop it.',
   'A possible central idea: "A city\'s new recycling program succeeded because it made participation easy for residents." A supporting idea could be a statistic showing participation rates before and after curbside bins were introduced.'),
  ('Is "the program collected 40 percent more recyclable material in its second year" an objective summary sentence or an opinion? Explain.',
   'It is objective — it reports a specific, verifiable statistic without added judgment; a subjective version might add a word like "impressively" or "finally."')],
 [('From Empty Lot to Open Market: How Two Neighbors Started Riverbend\'s Saturday Market (Part 1)', (
   '1. In 2019, the corner of Fifth and Poplar in Riverbend was an empty gravel lot used mostly for overflow parking during football games. By 2024, the same lot hosted a Saturday market drawing over 2,000 visitors a week and generating an estimated $340,000 a year for more than thirty small vendors. The central idea behind that change was simple: a market succeeds when it removes the specific barriers that keep small vendors from selling in the first place.\n\n'
   '2. The market began with two neighbors, Elena Vasquez and Tom Okafor, who ran small food businesses out of their homes but could not afford the vendor fees at the region\'s established farmers markets, which ranged from $75 to $150 per weekend. Vasquez and Okafor surveyed twelve other home-based sellers in Riverbend and found the same complaint from all twelve: high fees, not lack of demand, were keeping them from selling in public.\n\n'
   '3. Their first solution addressed that exact barrier. They approached the city about using the empty lot for free on Saturdays, arguing that an unused gravel lot generated zero tax revenue anyway. The city agreed to a six-month trial, waiving fees entirely and asking only that vendors carry basic liability insurance, which Vasquez and Okafor arranged as a discounted group policy for $40 a year per vendor.')),
  ('From Empty Lot to Open Market: How Two Neighbors Started Riverbend\'s Saturday Market (Part 2)', (
   '4. The second barrier they identified was visibility: even vendors who could afford to sell had no easy way to tell customers where or when. Vasquez built a simple text-alert list, and Okafor designed hand-painted signs for the five streets leading into the neighborhood. In the trial\'s first month, twelve vendors participated; by the sixth month, the number had grown to twenty-six, entirely by word of mouth and the text list, with no paid advertising.\n\n'
   '5. The third barrier surfaced only after the market was running: inconsistent hours. Some vendors opened at 8 a.m., others at 10, and customers who arrived expecting a full market sometimes found half the stalls empty. The market\'s informal vendor council, formed by the participants themselves in month four, voted to require a fixed 9 a.m. to 1 p.m. window for any vendor wanting a reserved spot.\n\n'
   '6. By the end of the six-month trial, the city\'s own data showed average Saturday foot traffic on Fifth and Poplar had risen from near zero to just over 2,000 visitors, and the city extended the arrangement indefinitely, still without vendor fees. Vasquez and Okafor now spend roughly five hours a week coordinating the market, work they describe as unpaid but far less time-consuming than the fee negotiations they used to face at other markets.\n\n'
   '7. Neither Vasquez nor Okafor has since raised a fee. When a city council member suggested a small fee to fund market improvements in 2023, the vendor council voted it down, 19 to 4, and instead proposed a voluntary $5 monthly contribution, which about half the vendors currently pay.'))],
 [('What explicit statistic does paragraph 1 give about the market\'s weekly visitors by 2024?', 'Over 2,000 visitors a week.'),
  ('What is the central idea stated explicitly in paragraph 1?', 'A market succeeds when it removes the specific barriers that keep small vendors from selling in the first place.'),
  ('What explicit barrier does paragraph 2 identify through the survey of twelve home-based sellers?', 'High vendor fees at established farmers markets, ranging from $75 to $150 per weekend, not a lack of customer demand.'),
  ('How does the fee-waiver solution in paragraph 3 directly support the central idea from paragraph 1?', 'It removes the specific barrier (high fees) identified in paragraph 2, directly matching the central idea that removing barriers, not simply creating a market, is what leads to vendor participation.'),
  ('What second barrier does paragraph 4 introduce, and how is it different from the fee barrier in paragraph 2?', 'The second barrier is visibility — customers not knowing where or when the market operated — which is different because it affects whether customers show up, not whether vendors can afford to participate.'),
  ('What explicit statistic in paragraph 4 shows the visibility solution\'s effect on vendor participation?', 'Vendor participation grew from twelve in the trial\'s first month to twenty-six by the sixth month.'),
  ('How does the vendor growth statistic in paragraph 4 develop the central idea further than the fee-waiver alone could?', 'It shows that removing one barrier (fees) was not enough by itself; solving the visibility barrier was also necessary for participation to keep growing, extending the central idea to include more than one kind of barrier.'),
  ('What third barrier does paragraph 5 identify, and who solved it?', 'Inconsistent vendor hours; the market\'s own informal vendor council, formed by the participants themselves, solved it by setting a fixed 9 a.m. to 1 p.m. window.'),
  ('Why is it significant for the central idea that the vendor council, not the city, solved the hours problem in paragraph 5?', 'It shows the barrier-removal approach extends to self-organization among vendors, not just outside city support, reinforcing that identifying and removing a specific barrier — regardless of who removes it — is what drives success.'),
  ('What explicit data does paragraph 6 give about foot traffic by the end of the trial?', 'Foot traffic rose from near zero to just over 2,000 visitors a week.'),
  ('How does paragraph 7\'s vote result (19 to 4) support the central idea established across the article?', 'The vendor council\'s strong vote against a new fee shows their continued belief that removing financial barriers, the very first barrier identified, remains central to the market\'s success, even years later.'),
  ('Which supporting idea most strongly develops the central idea: the fee waiver, the text-alert system, or the fixed hours rule? Justify your choice.', 'The fee waiver most strongly develops the central idea, because it was the original barrier identified through the founders\' survey and the direct basis for the central idea stated in paragraph 1; the other two solved barriers that emerged only after the market already existed.'),
  ('Explain how paragraphs 2 through 5 are organized to support the central idea, using the word "barrier" in your answer.', 'The paragraphs are organized as a sequence of barriers and their removal — fees, then visibility, then inconsistent hours — each paragraph identifying one specific barrier and the corresponding solution, which builds the central idea point by point rather than stating it once.'),
  ('Write one objective sentence summarizing paragraphs 2 and 3 (no opinions).', 'Vasquez and Okafor surveyed other home-based sellers, found that high vendor fees were the main barrier to selling, and arranged a fee-free trial with the city along with discounted liability insurance.'),
  ('Identify one word in this draft summary that is an opinion, not a fact: "The founders cleverly solved the visibility problem with simple, effective signs."', '"Cleverly" and "effective" are opinions about the quality of the solution, not neutral facts from the text.'),
  ('Write an objective one-sentence summary of paragraphs 6 and 7.', 'By the end of the trial, foot traffic had risen to over 2,000 visitors and the city extended the fee-free arrangement, which the vendor council later voted to keep by rejecting a proposed fee in 2023.'),
  ('Why would "the market grew because Riverbend residents love supporting local business" be an inappropriate central-idea statement for this article?', 'It is not supported as the article\'s central idea; the article specifically attributes the market\'s growth to the identification and removal of concrete barriers (fees, visibility, hours), not to general community sentiment, which the text never measures or claims.'),
  ('Combine paragraphs 1, 4, and 6 into a two-sentence objective summary tracing the central idea\'s development.', 'An empty gravel lot became a Saturday market after its founders identified and removed the specific barriers keeping small vendors from selling, starting with high fees and later addressing visibility. Vendor participation and customer foot traffic both grew steadily as each barrier was addressed, reaching over 2,000 weekly visitors by the end of the trial.'),
  ('What explicit detail from paragraph 2 shows the founders based their solution on evidence rather than a guess?', 'They surveyed twelve other home-based sellers and found the same complaint from all twelve, which grounded their solution in direct evidence rather than assumption.'),
  ('Trace the central idea\'s development across the entire article, citing at least three supporting ideas in the order they appear.', 'The central idea — that removing specific barriers drives a market\'s success — develops first through the fee waiver (paragraph 3), then through the visibility solutions of a text list and signage (paragraph 4), then through the vendor council\'s fixed-hours rule (paragraph 5), each addressing a different barrier the community had actually identified.')],
 600)

# ---------------------------------------------------------------- RL.8.3
add('rl83-dialogue-propels-action', 'The Line That Wasn\'t in the Script', 'RL.8.3',
 'Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character, or provoke a decision.',
 'Analyze how specific lines of dialogue or a specific incident in a literary text propel the plot forward, reveal something about a character, or provoke another character\'s decision.',
 'At grade 8, this standard asks you to zoom in on one specific line or incident and explain its effect — not the scene in general. A line can do more than one job at once: it can reveal character (show something true about who they are) while also propelling action (causing what happens next) or provoking a decision (forcing another character to choose).',
 [('In a story, a character who has stayed calm all scene suddenly says, "I am so tired of being the reasonable one." What might this single line reveal about the character?',
   'It could reveal hidden frustration or resentment the character has been suppressing, suggesting their calm behavior earlier was a performance rather than their true feeling.'),
  ('If that same line is followed by another character walking out of the room, what has the line done in terms of plot?',
   'It has propelled the action — caused a specific event (the other character leaving) that likely would not have happened without that line being spoken.')],
 [('The Line That Wasn\'t in the Script (Part 1)', (
   '1. Aaliyah had played Officer Reyes in the school play for six weeks of rehearsal, and for six weeks the climactic scene had gone the same way: her character confronts DeShawn\'s character, Marcus, and Marcus delivers his scripted apology — "I know I was wrong, and I\'m ready to face it" — before the lights dim.\n\n'
   '2. At the final dress rehearsal, with the director and half the cast\'s families watching from the back row, DeShawn reached the line and stopped. He looked at Aaliyah, and instead of the scripted apology, he said, "I\'m not sorry. I\'d do it again, and you know why."\n\n'
   '3. The stage manager\'s script, taped open to that page, sat useless in the wings. Aaliyah had exactly the length of one held breath to decide whether to stay in character or break the scene to fix DeShawn\'s mistake.\n\n'
   '4. She chose to stay in character. "Then I guess we\'re done pretending you\'re the good guy," she said, a line that existed nowhere in the script, and stepped between Marcus and the door instead of letting him exit as blocked.')),
  ('The Line That Wasn\'t in the Script (Part 2)', (
   '5. The rest of the cast froze, unsure whether to follow the printed blocking or whatever was happening in front of them. DeShawn, still in character, grabbed a prop chair and turned it toward Aaliyah instead of exiting stage left as rehearsed. "You don\'t get to decide that," he said. "Nobody made you the judge."\n\n'
   '6. Backstage, the director, Ms.Okoye, did not call "cut," though her hand hovered near the small flashlight she used to signal a stop. She let the scene run four more unscripted lines before Aaliyah, breathing hard, delivered something close enough to the original ending that the lighting cue still made sense.\n\n'
   '7. Afterward, DeShawn apologized to the cast for going off-script without warning anyone, admitting he had been carrying real frustration from an argument with his own older brother that afternoon and it had "come out sideways" during the scene. Aaliyah admitted she had been more afraid of an awkward silence onstage than of getting the words wrong.\n\n'
   '8. Ms. Okoye did not restore the original apology line for opening night. She kept DeShawn\'s defiant version and Aaliyah\'s unscripted response, telling the cast that the accidental scene had revealed something about both characters that the original script had been too tidy to show.'))],
 [('What explicit line has Marcus said the same way for six weeks, according to paragraph 1?', '"I know I was wrong, and I\'m ready to face it."'),
  ('What specific incident happens in paragraph 2 that breaks from six weeks of rehearsal?', 'DeShawn, in character as Marcus, stops before his scripted apology and instead says, "I\'m not sorry. I\'d do it again, and you know why."'),
  ('What decision does DeShawn\'s line force onto Aaliyah in paragraph 3?', 'She must decide, in the length of one held breath, whether to break character to fix his mistake or stay in the scene and respond within it.'),
  ('How does Aaliyah\'s line in paragraph 4, "Then I guess we\'re done pretending you\'re the good guy," propel the action of the scene?', 'It is an unscripted line that immediately leads her to step between Marcus and the exit instead of letting the blocked exit happen, physically changing the direction the scene was supposed to take.'),
  ('What does Aaliyah\'s choice to stay in character reveal about her as a performer, based on paragraph 4?', 'It reveals quick thinking and composure under pressure — rather than freezing or breaking the scene, she immediately generates a plausible in-character response.'),
  ('How does DeShawn\'s incident with the prop chair in paragraph 5 further propel the action beyond his original off-script line?', 'It escalates the improvised conflict physically, turning what began as one unexpected line into an ongoing, unscripted confrontation that the rest of the cast must now react to.'),
  ('What does DeShawn\'s new line in paragraph 5, "Nobody made you the judge," reveal about Marcus\'s character in this improvised version of the scene?', 'It reveals a more defiant, less repentant version of Marcus than the script originally showed, someone who resents being confronted rather than someone ready to apologize.'),
  ('What specific incident in paragraph 6 shows Ms. Okoye making a real-time decision about the unscripted scene?', 'She does not call "cut" even though her hand hovers near the signal flashlight, and she lets the scene run four more unscripted lines before intervening.'),
  ('How does Ms. Okoye\'s choice not to stop the scene immediately (paragraph 6) affect what happens next in the story?', 'It allows the improvised confrontation to continue long enough to become something Ms. Okoye later decides is worth keeping, rather than being cut short as a simple mistake.'),
  ('What explicit reason does DeShawn give in paragraph 7 for going off-script?', 'He had been carrying real frustration from an argument with his older brother that afternoon, and it "came out sideways" during the scene.'),
  ('What does DeShawn\'s explanation in paragraph 7 reveal about the relationship between an actor\'s real life and their performance?', 'It reveals that an actor\'s outside emotions can unintentionally shape a performance, showing that DeShawn\'s defiant improvisation was not a calculated acting choice but an unplanned result of his real frustration.'),
  ('What does Aaliyah\'s admission in paragraph 7 reveal about her real motivation during the scene?', 'It reveals her in-character response was driven partly by a practical fear of dead air onstage, not purely by inspired acting instinct, adding a more ordinary and honest motive to her quick thinking.'),
  ('What decision does Ms. Okoye make in paragraph 8, and how was it provoked by the earlier incident?', 'She decides to keep DeShawn\'s defiant version and Aaliyah\'s unscripted response for opening night; this decision was directly provoked by witnessing how the accidental scene revealed something about both characters that the original script had not.'),
  ('Identify one line of dialogue in the story that does more than one job (reveals character AND propels action), and explain both effects.', '"I\'m not sorry. I\'d do it again, and you know why" (paragraph 2) reveals a more defiant version of Marcus\'s character while also propelling the action by forcing Aaliyah into an immediate, unplanned decision about how to respond.'),
  ('How would the story\'s ending be different if Aaliyah had chosen to break character in paragraph 3 instead of staying in the scene?', 'The improvised confrontation would likely have stopped immediately, the original scripted apology might have simply been restarted, and Ms. Okoye would have had no unscripted material to consider keeping for opening night.'),
  ('Explain how the incident in paragraphs 2 through 5 provokes Ms. Okoye\'s decision in paragraph 8, citing at least two specific moments.', 'DeShawn\'s unscripted line in paragraph 2 and Aaliyah\'s improvised response in paragraph 4 together create an unplanned but compelling version of the scene; by letting it continue in paragraph 6 rather than stopping it, Ms. Okoye gathers enough material to decide in paragraph 8 that the improvised version reveals more about the characters than the original script did.'),
  ('What explicit detail in paragraph 6 shows the rest of the cast was as surprised as the audience by DeShawn\'s change?', 'The rest of the cast froze, unsure whether to follow the printed blocking or whatever was happening in front of them, showing they had no advance warning either.'),
  ('How does the incident of DeShawn grabbing the prop chair in paragraph 5 provoke a specific decision from Ms. Okoye described in paragraph 6?', 'It is one of the escalating unscripted moments that leads Ms. Okoye to keep her hand hovering near the stop signal rather than using it immediately, showing the incident is actively provoking her real-time decision about whether to intervene.'),
  ('Compare the incident that reveals character in paragraph 2 (DeShawn\'s line) to the incident that reveals character in paragraph 7 (his explanation). What does each reveal, and how are the revelations different?', 'Paragraph 2\'s incident reveals character indirectly, through Marcus\'s defiant in-scene words; paragraph 7\'s incident reveals DeShawn\'s real character directly, through his own honest, out-of-character explanation — one shows character through performance, the other through DeShawn speaking as himself.'),
  ('If Ms. Okoye had restored the original scripted apology line for opening night instead of keeping the improvised version, how would that change what the ending reveals about Marcus\'s character?', 'It would return to showing Marcus as straightforwardly repentant, losing the more complicated, defiant version of the character that the unscripted incident had revealed, and the story would no longer show how an unplanned incident can improve on a script.')],
 600)

# ---------------------------------------------------------------- RI.8.3
add('ri83-connections-distinctions', 'Two Towns, One Flood', 'RI.8.3',
 'Analyze how a text makes connections among and distinctions between individuals, ideas, or events (e.g., through comparisons, analogies, or categories).',
 'Analyze how an informational text draws connections and distinctions between individuals, ideas, or events, including through direct comparisons, analogies, or categories.',
 'At grade 8, this standard asks you to notice the specific method a text uses to relate or separate two or more things — comparison (showing similarity), distinction (showing difference), analogy (explaining one thing through a similar but different thing), or category (grouping things by a shared trait). Identify the method, not just that a connection exists.',
 [('A text says, "Both towns received the same amount of rainfall, but only one flooded." What method is being used, and what is it setting up?',
   'This is a comparison that sets up a contrast — since the shared cause (rainfall) was identical, the text is preparing to explain some other difference between the towns that explains the different outcome.'),
  ('A text explains a new policy by saying, "Think of it like a dam: it doesn\'t stop the water, it just controls when it\'s released." What method is this, and why might a writer choose it?',
   'This is an analogy, which explains an unfamiliar idea (the policy) through a more familiar comparison (a dam); a writer might choose it to make an abstract policy easier to picture concretely.')],
 [('Two Towns, One Flood (Part 1)', (
   '1. In April 2022, six inches of rain fell over two neighboring river towns, Ashford and Millport, in under eighteen hours — nearly identical totals recorded at weather stations nine miles apart. Ashford\'s river crested two feet above flood stage. Millport\'s crested four inches below it. The rainfall was the same; the outcomes were not.\n\n'
   '2. The two towns share a similar size, about 8,000 residents each, and both sit along the same river system, separated by a single upstream dam built in the 1950s. Ashford lies downstream of the dam; Millport lies upstream. That single geographic distinction — which side of the dam each town sits on — turned out to explain far more than the rainfall totals did.\n\n'
   '3. Millport\'s upstream position meant its excess water drained directly into the reservoir behind the dam, which engineers had deliberately kept three feet below capacity that spring specifically to absorb an unusually wet forecast. Ashford, downstream, received whatever the dam operators chose to release, on a schedule set by reservoir safety limits, not by Ashford\'s immediate needs.\n\n'
   '4. A hydrologist interviewed after the flood compared the dam\'s operation to a kitchen sink with only one working faucet: "Upstream is like turning the tap — you control how much comes out and when. Downstream, you\'re just the drain, and the drain doesn\'t get a vote."')),
  ('Two Towns, One Flood (Part 2)', (
   '5. That analogy captures a real distinction in the two towns\' options. Millport\'s town council could and did request the dam operators delay a scheduled release by six hours, buying time for its own storm drains to catch up. Ashford\'s council had no equivalent lever; the release schedule downstream was set entirely by the dam operators\' calculations, not by any request Ashford could make.\n\n'
   '6. Researchers studying the flood later grouped river towns nationally into two categories based on this same upstream-downstream distinction, finding that downstream towns experienced 60 percent more flood damage per capita than upstream towns along regulated rivers, even when rainfall totals were statistically similar.\n\n'
   '7. The comparison between Ashford and Millport also revealed a connection the two towns share despite their different outcomes: both had underfunded their storm-drain systems by similar amounts over the previous decade, a shared factor that worsened flooding in both towns even though it did not, by itself, explain why only one town crossed flood stage.\n\n'
   '8. After the flood, Ashford\'s council proposed a formal notification agreement with the dam operators, modeled explicitly on Millport\'s existing arrangement — an attempt to close the very distinction between the two towns that the flood had exposed.'))],
 [('What explicit rainfall comparison does paragraph 1 make between Ashford and Millport?', 'Both towns received nearly identical rainfall totals, about six inches in under eighteen hours, recorded at weather stations nine miles apart.'),
  ('What method does paragraph 1 use when it says "The rainfall was the same; the outcomes were not"? What is this method setting up?', 'This is a direct comparison used to create a contrast; it sets up the article\'s explanation that some factor other than rainfall must explain the different outcomes.'),
  ('What explicit geographic distinction does paragraph 2 identify between the two towns?', 'Ashford lies downstream of the dam, and Millport lies upstream of it.'),
  ('How does paragraph 2 connect the towns before distinguishing them? Name both the connection and the distinction.', 'The connection is that the towns are similar in size (about 8,000 residents each) and sit along the same river system; the distinction is their position relative to the dam, upstream versus downstream.'),
  ('What explicit detail in paragraph 3 explains why Millport\'s upstream position helped during the flood?', 'The reservoir behind the dam had deliberately been kept three feet below capacity that spring to absorb an unusually wet forecast, giving Millport\'s excess water somewhere to go.'),
  ('What category of control does paragraph 3 say Ashford lacked, compared to Millport?', 'Ashford had no control over water release timing; releases were set by the dam operators based on reservoir safety limits, not by Ashford\'s needs.'),
  ('Identify the analogy used in paragraph 4 and explain what two things it compares.', 'The hydrologist compares the dam system to a kitchen sink with one working faucet, comparing the upstream town\'s control (turning the tap) to the downstream town\'s lack of control (being "just the drain").'),
  ('Why might the hydrologist have chosen a kitchen sink analogy instead of simply restating the engineering facts from paragraph 3?', 'A kitchen sink is a familiar, everyday image that makes an unfamiliar engineering relationship (upstream versus downstream water control) easier for a general reader to picture and understand quickly.'),
  ('What explicit action does paragraph 5 (Part 2) describe Millport\'s council taking that Ashford\'s council could not?', 'Millport\'s council requested and received a six-hour delay in a scheduled dam release, buying time for its storm drains to catch up.'),
  ('What category do researchers create in paragraph 6, and what distinction does it track nationally?', 'Researchers grouped river towns nationally into upstream and downstream categories along regulated rivers, tracking the distinction in flood damage per capita between the two categories.'),
  ('What explicit statistic supports the researchers\' categorization in that paragraph?', 'Downstream towns experienced 60 percent more flood damage per capita than upstream towns, even when rainfall totals were statistically similar.'),
  ('What connection does paragraph 7 identify between Ashford and Millport that goes against the upstream/downstream distinction?', 'Both towns had similarly underfunded their storm-drain systems over the previous decade, a shared weakness despite their different flood outcomes.'),
  ('Why is the connection in paragraph 7 important for a complete understanding of the flood, even though it does not explain the difference in outcomes?', 'It shows the flood was not caused by a single distinction alone; a shared, unrelated weakness (underfunded storm drains) worsened conditions in both towns even as the upstream/downstream distinction explains why only one town crossed flood stage.'),
  ('What explicit action does Ashford\'s council take in paragraph 8, and what distinction is it specifically trying to close?', 'Ashford\'s council proposes a formal notification agreement with the dam operators, modeled on Millport\'s existing arrangement, trying to close the upstream/downstream control distinction identified earlier in the article.'),
  ('Explain how the article uses comparison, distinction, and analogy together across paragraphs 1 through 4 to build its explanation.', 'The article first uses comparison to show the rainfall was the same (paragraph 1), then identifies the key distinction of upstream versus downstream position (paragraph 2), then uses an analogy (the kitchen sink, paragraph 4) to make that engineering distinction easy to picture, building from data to explanation to a relatable image.'),
  ('Which is a stronger piece of evidence for the article\'s explanation: the kitchen sink analogy or the 60 percent damage statistic? Justify your answer.', 'The 60 percent damage statistic is stronger evidence, because it is a measured, verifiable finding across many towns, while the analogy is only an explanatory device that makes the idea easier to understand and proves nothing on its own.'),
  ('A reader claims the flood happened only because Ashford is downstream. Using evidence from the article, explain why this oversimplifies the article\'s explanation.', 'This oversimplifies it because paragraph 7 shows both towns shared an unrelated weakness, underfunded storm drains, that worsened flooding in both places; the upstream/downstream distinction explains the difference in outcome, but it is not the article\'s only identified cause.'),
  ('Compare how paragraph 2 and paragraph 8 both use the idea of distinction, but for different purposes.', 'Paragraph 2 uses distinction to explain why the flood outcomes differed, while paragraph 8 uses the same distinction to justify a proposed solution, showing the article moving from diagnosing a problem to addressing it, using the same core distinction both times.'),
  ('Explain how the article\'s use of categories (paragraph 6) strengthens the individual comparison between Ashford and Millport made earlier in the article.', 'By showing that the upstream/downstream damage pattern holds true nationally across many towns, not just Ashford and Millport, the categorization strengthens the article\'s claim that the two towns\' different outcomes were not a coincidence specific to them, but part of a broader, measurable pattern.'),
  ('Why does the article wait until paragraph 8 to describe Ashford\'s proposed solution, rather than introducing it earlier alongside the initial comparison in paragraph 1?', 'The article needs to first establish the distinction (upstream/downstream), the analogy explaining it, the national statistic confirming it, and the shared storm-drain connection before a proposed solution would make sense to the reader; introducing it earlier would come before the article has built the evidence to justify it.')],
 600)

# ---------------------------------------------------------------- RL.8.4
add('rl84-word-choice-tone', 'What the Order Didn\'t Say', 'RL.8.4',
 'Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of specific word choices on meaning and tone, including analogies or allusions to other texts.',
 'Determine figurative and connotative meanings of words and phrases in a literary text, and analyze how specific word choices shape meaning and tone.',
 'Denotation is a word\'s dictionary meaning; connotation is the feeling or association it carries beyond that meaning. Figurative language (metaphor, simile, personification) means something beyond its literal words. At grade 8, comparing word choices across two texts about the same event is a powerful way to see how word choice alone can create very different tones.',
 [('Compare the connotation of "the family relocated" versus "the family fled." Both can describe the same event — how do the connotations differ?',
   '"Relocated" carries a calm, planned, even bureaucratic connotation, suggesting control and choice, while "fled" carries urgency and fear, suggesting the family had little choice and left in danger.'),
  ('In the phrase "the smoke crawled over the ridge like something that knew where it was going," what figurative device is used, and what tone does it create?',
   'This is a simile (and personification, since smoke is given intention), and it creates an ominous, threatening tone by making the smoke seem deliberate and predatory rather than simply a natural weather event.')],
 [('Evacuation Order 14-B', (
   'RIDGELINE COUNTY OFFICE OF EMERGENCY MANAGEMENT\nEVACUATION ORDER 14-B\nEffective immediately, all residents of Zones 3 through 6 are directed to relocate to designated shelters. Residents should gather essential documents and medications and proceed to Route 9 southbound. Non-compliance may result in restricted emergency service access. This order remains in effect until further notice.')),
  ('What the Order Didn\'t Say', (
   '1. The order came through Priya\'s phone at 6:14 a.m., a flat gray banner with no exclamation points, no color, nothing to suggest it was the reason her mother was already dragging the fireproof document box down the stairs two at a time. "Relocate to designated shelters." As if the house were a piece of furniture they were simply moving to a different room.\n\n'
   '2. Outside, the sky had turned a color Priya had never had a word for before that morning — not orange exactly, more like the inside of a bruise, and the smoke crawled over the ridge like something that knew where it was going. The order had called it "reduced visibility due to active conditions." Priya thought that was like calling a wildfire "a warm afternoon."\n\n'
   '3. Her little brother, Theo, wanted to know if their house counted as "essential documents." Their mother said no, gently, the kind of gentle that Priya recognized as the sound of someone keeping a much louder feeling folded up small. Theo asked again anyway, holding his stuffed rabbit like it might answer for him.\n\n'
   '4. They joined Route 9 southbound along with what felt like the entire ridge, headlights strung out ahead of them like a sentence with no punctuation, just comma after comma of red taillights with no end in sight. The order had said "proceed." It had not said anything about the woman two cars ahead who kept getting out to look back at the smoke, or the way the radio DJ\'s voice cracked once, just once, before he caught it and went back to reciting the shelter addresses in his steady announcer voice.\n\n'
   '5. "Restricted emergency service access," the order had warned, if they did not comply. Priya turned the phrase over and over. It sounded like a rule about a parking lot, not a sentence about whether help would come if they stayed. She understood, suddenly and completely, that the order had been written by someone whose job was to be understood by everyone, and that being understood by everyone sometimes meant sounding like it mattered to no one.\n\n'
   '6. At the shelter, a volunteer handed them water bottles and said, "You\'re safe now," and that phrase, unlike anything in the order, was the first thing all morning that had sounded like it was written for Priya specifically, and not for Zones 3 through 6.'))],
 [('What explicit phrase does the official order use to describe leaving one\'s home, according to paragraph 1?', '"Relocate to designated shelters."'),
  ('What is the connotation of "relocate" as Priya interprets it in paragraph 1, and how does that differ from what is actually happening?', 'Priya interprets "relocate" as sounding calm and administrative, like moving furniture to a different room, when the actual event is an urgent, frightening evacuation from danger.'),
  ('Identify the simile in paragraph 2 describing the smoke, and explain what it suggests about the smoke\'s behavior.', '"The smoke crawled over the ridge like something that knew where it was going" is a simile that suggests intention and menace, as if the smoke were a living thing deliberately advancing rather than simply spreading with the wind.'),
  ('How does Priya\'s comparison in paragraph 2 ("calling a wildfire \'a warm afternoon\'") reveal her opinion of the order\'s word choice?', 'It reveals she thinks the order\'s phrase "reduced visibility due to active conditions" dangerously understates the danger, comparing it to an equally absurd understatement of a wildfire as pleasant weather.'),
  ('What does the phrase "the kind of gentle that Priya recognized as the sound of someone keeping a much louder feeling folded up small" suggest about their mother\'s emotional state?', 'It suggests their mother is suppressing fear or panic beneath a calm exterior for Theo\'s sake, and that her gentleness is a controlled performance rather than an absence of strong feeling.'),
  ('Identify the figurative comparison in paragraph 4 describing the traffic, and explain what it conveys about the scene.', 'The headlights are compared to "a sentence with no punctuation, just comma after comma of red taillights with no end in sight," conveying an overwhelming, unending line of evacuating cars with no clear resolution in sight.'),
  ('What two specific incidents in paragraph 4 does the narrator note that the official order\'s language never captures?', 'A woman two cars ahead repeatedly getting out to look back at the smoke, and a radio DJ\'s voice cracking once before he composes himself and continues reciting shelter addresses.'),
  ('What is the denotative meaning of "restricted emergency service access," and what connotation does Priya sense underneath it in paragraph 5?', 'Denotatively, it means emergency responders may not be able to reach non-compliant residents; Priya senses underneath it the real, frightening possibility that help might not come at all, though the phrase itself sounds bureaucratic and mild.'),
  ('Why does Priya compare the phrase "restricted emergency service access" to "a rule about a parking lot"?', 'She makes this comparison to highlight how mismatched the phrase\'s mild, procedural tone is to the life-or-death situation it actually describes.'),
  ('What insight does Priya reach in paragraph 5 about why the order is written the way it is?', 'She realizes the order was written to be understood by everyone equally, and that this kind of universal, neutral language can end up sounding like it matters to no one in particular, even though it is meant for everyone.'),
  ('How does the volunteer\'s phrase "You\'re safe now" in paragraph 6 contrast in tone with the official order\'s language throughout the story?', 'Unlike the order\'s flat, procedural phrases, the volunteer\'s words are warm and personal, addressed to Priya specifically rather than to an entire numbered zone, creating a tone of individual care instead of bureaucratic instruction.'),
  ('Why does the narrator specifically note that the volunteer\'s phrase felt "written for Priya specifically, and not for Zones 3 through 6"?', 'It emphasizes the story\'s larger point about word choice and tone: official, general language can technically communicate the same information as warm, specific language, but it does not make a listener feel seen or cared for the way personal language does.'),
  ('Compare the tone of the official order text to the tone of Priya\'s narrative. Use one word-choice example from each to support your comparison.', 'The order\'s tone is flat and procedural, shown by phrases like "proceed to Route 9 southbound"; Priya\'s narrative is vivid and emotional, shown by figurative language like comparing the smoke to something that "knew where it was going."'),
  ('Choose one phrase from the official order and explain how its word choice avoids alarming readers, even though the situation is dangerous.', '"Reduced visibility due to active conditions" avoids words like "fire," "danger," or "smoke," using vague, technical-sounding language that describes a hazardous situation without naming it directly, which likely reduces panic but also reduces urgency.'),
  ('If the order had instead said "a dangerous wildfire is approaching your home," how might the tone and effect on residents be different from the actual order\'s wording?', 'It would create a more urgent, alarming tone that clearly names the danger, which might prompt faster compliance from residents but could also risk causing panic that the order\'s calmer, more procedural language was likely designed to avoid.'),
  ('What is the denotative meaning of "reduced visibility due to active conditions," and what does Priya believe it is designed to avoid saying directly?', 'Denotatively, it means smoke is making it hard to see, caused by the fire\'s ongoing spread; Priya believes it is designed to avoid saying "wildfire" or "fire" directly, softening the danger through vague, technical phrasing.'),
  ('Identify the figurative language in "a color Priya had never had a word for before that morning — not orange exactly, more like the inside of a bruise," and explain what feeling it conveys.', 'The comparison of the sky to "the inside of a bruise" is a simile that conveys a sickly, painful, unnatural feeling, suggesting the sky itself looks injured or wrong.'),
  ('Why might the author have chosen to include the official order as a separate, first text before Priya\'s narrative, rather than only telling the story from Priya\'s point of view?', 'Presenting the order\'s flat, procedural language first lets readers directly compare its tone to Priya\'s vivid, emotional narrative that follows, making the contrast in word choice and tone much clearer than if only one version were given.'),
  ('Choose one word from the official order and explain both its technical/denotative meaning and the connotation it might carry for a frightened resident.', 'Answers vary; for example, "designated" technically just means officially assigned or specified, but to a frightened resident it might carry a connotation of cold, impersonal bureaucracy at a moment of personal crisis.'),
  ('Trace how the story\'s tone shifts from paragraph 1 to paragraph 6, citing specific word choices at the beginning and end.', 'The story begins with a flat, confused tone as Priya reads the bureaucratic order ("relocate to designated shelters," paragraph 1) and ends with a warmer, more personal tone at the shelter, when the volunteer\'s words "You\'re safe now" (paragraph 6) finally sound, in Priya\'s words, "written for Priya specifically."')],
 600)

# ---------------------------------------------------------------- RI.8.4
add('ri84-technical-word-choice', 'Words in the White Coat', 'RI.8.4',
 'Determine the meaning of words and phrases as they are used in a text, including figurative, connotative, and technical meanings; analyze the impact of specific word choices on meaning and tone, including analogies or allusions to other texts.',
 'Determine figurative, connotative, and technical meanings of words and phrases in an informational text, and analyze how specific word choices shape meaning and tone.',
 'Informational texts often mix technical meanings (precise, field-specific definitions) with connotative meanings (the feelings a word carries). At grade 8, notice when a writer chooses a more clinical, technical word versus a more everyday or emotionally loaded one, and consider what effect that choice has on the reader.',
 [('A medical report could describe a patient as "obese" or as "carrying extra weight." What is the difference between these two word choices?',
   '"Obese" is a precise technical/clinical term with a specific medical definition, while "carrying extra weight" is a softer, more everyday phrase; the technical term sounds more clinical and less personal, while the everyday phrase may feel gentler but less precise.'),
  ('If a doctor says a treatment has a "statistically significant effect," what technical meaning does "significant" have here that differs from its everyday connotation of "important" or "large"?',
   'In statistics, "significant" technically means the result is unlikely to be due to random chance, which is a specific mathematical claim; it does not necessarily mean the effect is large or clinically important, which is how the word is often used in everyday speech.')],
 [('Words in the White Coat: How Doctors Choose Language for Patients (Part 1)', (
   '1. When Dr. Elena Morrow was a medical resident, a senior physician told her something she still repeats to her own students two decades later: "You have exactly one chance to choose the first word a patient hears about their diagnosis, and that word will color everything they hear after it." The word, in that case, was "mass." Not "tumor," not "growth," not "cancer" — just "mass," a technically accurate but deliberately neutral term used until further testing could clarify what kind of mass it was.\n\n'
   '2. Medical language operates on at least two levels at once: the technical level, where a word has a precise, field-specific definition regardless of how it sounds, and the connotative level, where the same word carries emotional weight a patient will feel immediately. "Tumor" is technically neutral — it simply means an abnormal mass of tissue, which can be benign or malignant — but its everyday connotation is almost entirely frightening, often assumed to mean cancer even when it does not.\n\n'
   '3. This gap between technical meaning and connotation creates real dilemmas. A 2021 survey of oncologists found that 68 percent said they deliberately chose less alarming words during an initial diagnosis conversation, even when a more clinical term was technically more precise, specifically to avoid overwhelming a patient before they were ready to absorb full information.')),
  ('Words in the White Coat: How Doctors Choose Language for Patients (Part 2)', (
   '4. Word choice matters even in written reports patients read themselves. Dr. Morrow points to the shift many hospitals have made from "obese" to "BMI above 30" or "elevated BMI" in visit summaries. The number is more technical and, according to Morrow, "somehow feels less like a judgment and more like a measurement," even though both phrases describe the identical clinical finding.\n\n'
   '5. Some word choices rely on analogy rather than technical precision. Dr. Morrow often describes chemotherapy to patients as "clearing a garden that has both the plant you want and the weeds choking it out — the tools cannot always tell the difference." She avoids the still-common military analogy of "fighting" or "battling" cancer, which she says can unintentionally suggest a patient who dies from the disease somehow "lost," as if survival were purely a matter of effort.\n\n'
   '6. Technical terms are not always more comforting than emotional ones. When Dr. Morrow tells a patient a treatment showed a "statistically significant" improvement, some patients hear "significant" and assume a dramatic, life-changing result, when the technical meaning only confirms the result was unlikely to be due to chance and says nothing about its actual size.\n\n'
   '7. Morrow\'s current guidance to her residents is not to avoid technical language altogether, but to name the gap out loud: to say, in effect, "here is the precise medical term, and here is what it does and does not mean for you," treating word choice itself as part of patient care rather than a formality that happens before the real conversation begins.'))],
 [('What explicit word does paragraph 1 identify as Dr. Morrow\'s first choice when a diagnosis is still uncertain?', '"Mass."'),
  ('What technical reason does paragraph 1 give for choosing "mass" instead of more specific terms?', 'It is technically accurate but deliberately neutral, used until further testing can clarify what kind of mass it actually is.'),
  ('Explain the distinction paragraph 2 draws between a word\'s technical meaning and its connotative meaning, using "tumor" as the example.', 'Technically, "tumor" simply means an abnormal mass of tissue that can be benign or malignant; connotatively, most patients hear the word and immediately assume cancer, even though that is not what the technical definition requires.'),
  ('What explicit statistic does paragraph 3 provide about oncologists\' word choices during initial diagnosis conversations?', '68 percent of oncologists surveyed in 2021 said they deliberately chose less alarming words, even when a more clinical term was technically more precise.'),
  ('Why, according to paragraph 3, might a doctor choose a less precise word over a more technically accurate one?', 'To avoid overwhelming a patient with alarming language before the patient is ready to absorb full information about their condition.'),
  ('What explicit shift in terminology does paragraph 4 describe hospitals making, and what technical meaning does the new term have?', 'A shift from "obese" to "BMI above 30" or "elevated BMI," where BMI is a specific, calculated numerical measurement rather than a descriptive label.'),
  ('According to Dr. Morrow\'s quote in paragraph 4, what is the connotative effect of using a number ("BMI above 30") instead of a descriptive word ("obese")?', 'It "feels less like a judgment and more like a measurement," even though both phrases technically describe the same clinical finding.'),
  ('Identify the analogy Dr. Morrow uses to describe chemotherapy in paragraph 5, and explain what two things it compares.', 'She compares chemotherapy to "clearing a garden that has both the plant you want and the weeds choking it out," comparing healthy and cancerous cells to desired plants and weeds, and the imprecision of treatment to a gardening tool that cannot always tell them apart.'),
  ('Why does Dr. Morrow avoid the "fighting" or "battling" analogy for cancer, according to paragraph 5?', 'She says it can unintentionally suggest that a patient who dies from the disease somehow "lost," implying survival is purely a matter of effort, which she considers an unfair and inaccurate connotation.'),
  ('What is the technical meaning of "statistically significant," as explained in paragraph 6?', 'It technically means the result is unlikely to be due to random chance; it says nothing about how large or dramatic the actual effect is.'),
  ('How does the everyday connotation of "significant" in paragraph 6 differ from its technical statistical meaning, and why does this matter for patients?', 'Everyday "significant" suggests something large or dramatic, while the technical meaning only confirms the result is not due to chance; this matters because patients may wrongly expect a dramatic improvement based on the everyday connotation alone.'),
  ('What is Dr. Morrow\'s current guidance to her residents, according to paragraph 7?', 'Not to avoid technical language, but to explicitly name the gap between the technical term and what it does and does not mean for the patient.'),
  ('Why does the article end with Dr. Morrow\'s guidance in paragraph 7 rather than with the chemotherapy analogy in paragraph 5? What does this suggest about the article\'s central point?', 'Ending with her guidance suggests the article\'s central point is not just that word choice matters, but that doctors should be deliberate and transparent about it, treating the choice of words as an active, ongoing part of patient care rather than a single clever word or analogy.'),
  ('Compare the tone created by "mass" (paragraph 1) to the tone created by "tumor" (paragraph 2), even though both can technically describe the same thing.', '"Mass" creates a calm, neutral, even slightly vague tone, buying time before a clearer picture emerges, while "tumor" creates an alarmed tone because of its strong connotative association with cancer, even when the underlying finding is identical.'),
  ('A reader claims doctors should always use the most technically precise word possible, regardless of connotation. Using evidence from the article, explain why Dr. Morrow\'s practice complicates this claim.', 'Dr. Morrow deliberately avoids the most alarming precise term in initial conversations (paragraph 1) and studies show most oncologists do the same (paragraph 3), showing that in practice, doctors weigh a word\'s emotional impact alongside its technical precision rather than always choosing the most exact term available.'),
  ('What is the technical, field-specific meaning of "BMI," and how does paragraph 4 suggest the number format changes the tone of a clinical finding compared to a descriptive word?', 'BMI (body mass index) is a specific numerical measurement calculated from height and weight; paragraph 4 suggests presenting it as a number feels more neutral and measurement-like, while a descriptive word like "obese" can feel more like a personal judgment, even though both describe the same finding.'),
  ('Explain the figurative comparison in paragraph 5 between chemotherapy and gardening, identifying what each part of the analogy represents.', 'The "plant you want" represents healthy cells, the "weeds choking it out" represent cancerous cells, and "the tools cannot always tell the difference" represents chemotherapy\'s inability to perfectly distinguish healthy from cancerous cells, explaining a complex medical limitation through a familiar, everyday image.'),
  ('What connotation does the "fighting" or "battling" analogy for cancer carry, according to Dr. Morrow in paragraph 5, and why does she consider it potentially unfair?', 'It carries a connotation that surviving is a matter of effort or willpower, like winning a fight; she considers it unfair because it implies a patient who dies somehow "lost" or did not try hard enough, when survival often depends on factors beyond a patient\'s control.'),
  ('Compare the connotative effect of the gardening analogy in paragraph 5 to the connotative effect of the "fighting" analogy she avoids. Why might one feel gentler than the other?', 'The gardening analogy focuses on the imprecision of a tool doing careful work, which feels gentler and more forgiving, while the fighting analogy frames the patient as personally responsible for winning or losing, which can feel more like praise or blame directed at the patient.'),
  ('Explain how the article\'s title, "Words in the White Coat," uses connotation to introduce its subject before the reader reaches paragraph 1.', 'The "white coat" is a strong visual and cultural symbol of medical authority and expertise, so pairing it with "words" in the title immediately signals that the article is specifically about how that authority is expressed and shaped through language choices, not just medical facts themselves.')],
 600)
