"""Original Grade 8 NC ELA reading-standard packets (RL.8.x and RI.8.x).

Same format as rl_ri_grade7_content.py: original passages written for a more
mature (8th-grade) reading level, plus a 20-item Q&A bank per standard with
reasoning in every answer. No released-test or third-party material is used.
Standard codes and text are the Common Core Reading Literature / Reading
Informational Text standards for grade 8, which North Carolina's Standard
Course of Study adopts under the same numbering.
"""
NC = 'https://www.thecorestandards.org/ELA-Literacy/'
ROWS = []


def add(slug, title, code, standard_text, objective, lesson, models, texts, items, price):
    assert len(items) == 20, (slug, len(items))
    assert len(models) == 2
    assert len(texts) in (1, 2), (slug, len(texts))
    strand = 'RL' if code.startswith('RL') else 'RI'
    num = code.split('.')[-1]
    ROWS.append(dict(id='nc-g8-' + slug, title=title, state='North Carolina', grade='8', subject='Reading',
        standard=code + ' — ' + standard_text, objective=objective,
        source=NC + strand + '/8/' + num + '/', resourceType='Complete ELA practice packet',
        lesson=lesson, models=models, texts=texts,
        items=[{'q': q, 'answer': a, 'work': a} for q, a in items], price=price))


# ---------------------------------------------------------------- RL.8.1
add('rl81-textual-evidence', 'Evidence and Inference Lab', 'RL.8.1',
 'Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.',
 'Cite the textual evidence that most strongly supports an analysis of explicit statements and inferences drawn from a literary text.',
 'Explicit evidence is stated directly in the text; an inference is a reasonable conclusion built from evidence plus what a reader already knows. At grade 8, "most strongly supports" means choosing the single best piece of evidence, not just any evidence that fits — weigh competing details and explain why one supports the analysis better than another.',
 [('Paragraph 2 says Marcus "read the acceptance letter four times, then folded it into his back pocket instead of showing anyone." What is the strongest evidence for an inference that he is unsure how to feel about the news?',
   'The detail that he read it four times but told no one is the strongest evidence — rereading suggests he is still processing the news, and folding it away instead of sharing it suggests he is not ready to react publicly, which together support uncertainty rather than simple excitement or disappointment.'),
  ('Between "the gym was hot" and "she wiped her palms on her shorts three times before the serve," which detail more strongly supports an inference about nervousness, and why?',
   'The second detail more strongly supports nervousness because it is a specific, repeated physical action tied directly to the moment of pressure, while "the gym was hot" is a general environmental fact that could support many different inferences.')],
 [('The Acceptance Letter', (
   '1. Marcus had applied to the magnet arts high school without telling his older brother, Dante, who had been rejected from the same program two years earlier and had not mentioned it since. Marcus kept his own application folded inside a library book so it would not turn up in a drawer.\n\n'
   '2. The letter came on a Tuesday, while Dante was at practice. Marcus read the acceptance letter four times, then folded it into his back pocket instead of showing anyone. He went to his room and closed the door, which he almost never did.\n\n'
   '3. At dinner, their mother asked if anything interesting had happened that day. Marcus said no. Dante, half-listening, asked to be passed the rice. Marcus passed it and said nothing else for the rest of the meal.\n\n'
   '4. Over the next week, Marcus carried the letter with him — to school, to the bus stop, once even into the shower, where it sat on the sink until he remembered and moved it. He did not read it again. He also did not throw it away.\n\n'
   '5. On Saturday, Dante found him in the garage, sitting on an overturned bucket, the letter open on his knee. "You\'ve had that a week," Dante said. It was not a question. Marcus had not heard him come in.\n\n'
   '6. "I didn\'t want it to be a thing," Marcus said. "You didn\'t get in, and I—" He stopped. Dante sat down on a second bucket, close enough that their shoulders nearly touched.\n\n'
   '7. "I got in your way for two years without meaning to," Dante said. "Read it out loud. I want to hear how it sounds when it\'s actually happening to someone." Marcus looked at him for a long moment before he understood that Dante meant it.\n\n'
   '8. Marcus read the letter aloud, once, in the garage, with the door up and the evening light coming in sideways across the concrete. When he finished, Dante didn\'t say anything about his own rejection at all. He just said, "You should tell Mom tonight," and meant it kindly.\n\n'
   '9. That night at dinner, Marcus told her. Dante, across the table, was the first to smile.'))],
 [('What does paragraph 1 state explicitly about how Marcus applied to the magnet school?', 'He applied without telling Dante, and kept the application folded inside a library book so it would not be found.'),
  ('What is the strongest evidence that Marcus is anxious about how Dante will react to the news? Cite it and explain why it is the strongest choice.', 'The strongest evidence is that he hid the application inside a library book (paragraph 1) and later hid the acceptance letter in his pocket instead of telling anyone (paragraph 2); these two deliberate acts of concealment, both aimed at avoiding Dante finding out, more strongly support anxiety than a single detail like closing his door would alone.'),
  ('What explicit action does Marcus take with the letter in paragraph 2?', 'He reads it four times, then folds it into his back pocket instead of showing anyone, and closes his bedroom door.'),
  ('Which detail from paragraph 3 most strongly supports an inference that Marcus is deliberately hiding something at dinner, and why is it stronger than the fact that he "said no"?', '"Marcus... said nothing else for the rest of the meal" is stronger, because staying unusually silent for an entire meal is a sustained behavior change, while a single "no" answer alone could simply mean nothing happened that day.'),
  ('What explicit detail in paragraph 4 shows Marcus cannot decide what to do with the letter?', 'He carries it everywhere for a week, including into the shower, but does not read it again and does not throw it away.'),
  ('What can you infer about why Marcus does not throw the letter away, even though he also will not talk about it? Cite the strongest evidence.', 'He likely still wants to keep the acceptance real to himself even while afraid to share it; the strongest evidence is that he carries it everywhere, including into the shower (paragraph 4), which shows the letter matters enough to stay physically close even without being discussed.'),
  ('What explicit statement in paragraph 5 shows Dante already suspected something?', '"You\'ve had that a week," Dante said — stated as fact, not a question, showing he already knew or had guessed.'),
  ('Between "It was not a question" and "Marcus had not heard him come in," which more strongly supports the inference that Dante had been quietly paying attention to Marcus all week? Explain.', '"It was not a question" more strongly supports it, because it shows Dante already had enough information to state a fact rather than ask, which requires him to have been observing Marcus over time, while "Marcus had not heard him come in" only shows Marcus was distracted in that moment.'),
  ('What explicit reason does Marcus give in paragraph 6 for hiding the letter?', 'He says he "didn\'t want it to be a thing," and starts to reference Dante not getting in before stopping himself.'),
  ('What can you infer about Dante\'s feelings toward his own rejection from paragraph 7? Cite the strongest evidence.', 'He seems to have made peace with it or wants to face it directly rather than avoid it; the strongest evidence is his direct request, "Read it out loud. I want to hear how it sounds when it\'s actually happening to someone," which shows he is choosing to engage with the painful topic rather than avoid it.'),
  ('What explicit physical detail in paragraph 7 shows a shift toward closeness between the brothers?', 'Dante sits down on a second bucket, close enough that their shoulders nearly touch.'),
  ('Which is the stronger evidence that Dante has genuinely moved past resentment: sitting close to Marcus, or asking him to read the letter aloud? Explain your reasoning.', 'Asking Marcus to read the letter aloud is stronger evidence, because it is an active choice to face the source of possible resentment directly, while sitting close is a smaller, more passive gesture that could occur without resolving deeper feelings.'),
  ('What explicit detail describes the setting as Marcus reads the letter aloud in paragraph 8?', 'The garage door is up and the evening light is coming in sideways across the concrete.'),
  ('What can you infer from Dante saying nothing about his own rejection after Marcus finishes reading? Cite evidence.', 'It suggests Dante is intentionally keeping the moment focused on Marcus rather than making it about himself; paragraph 8 states he "didn\'t say anything about his own rejection at all" immediately after the reading, which is a deliberate omission given the topic\'s relevance.'),
  ('What explicit words does Dante use to encourage Marcus at the end of paragraph 8?', '"You should tell Mom tonight."'),
  ('What is the strongest evidence in the whole story that Dante\'s support is sincere rather than reluctant? Justify your choice.', 'The strongest evidence is that Dante is "the first to smile" when Marcus tells their mother (paragraph 9); a genuine, immediate positive reaction at the emotional climax carries more weight than his earlier words alone, since actions in the story\'s final moment confirm what his words suggested.'),
  ('Explain the difference between explicit and inferred information using two examples from this story.', 'Explicit: the text directly states Marcus read the letter four times (paragraph 2). Inferred: the reader must conclude from his silence and hiding behavior that he feels anxious or unsure, since the story never states his emotions directly.'),
  ('A classmate claims the story is only about sibling rivalry. Using the strongest textual evidence, explain why that analysis is incomplete.', 'The story is more about reconciliation than rivalry; the strongest evidence against a rivalry-only reading is Dante\'s statement, "I got in your way for two years without meaning to" (paragraph 7), which shows him taking responsibility and moving toward connection rather than continuing to compete.'),
  ('Identify one place in the story where two different inferences could reasonably be drawn from the same evidence, and explain both.', 'Dante finding Marcus in the garage (paragraph 5) could support either "Dante has been quietly worried about Marcus" or "Dante happened to walk in by chance"; the story leans toward the first because Dante already knows how long Marcus has had the letter, which is unlikely to be coincidence.'),
  ('Write one full inference about Dante, and identify the single strongest piece of evidence that supports it, explaining why it beats at least one other possible piece of evidence.', 'Answers vary; require a clear inference about Dante plus one specific cited detail, with an explanation of why that detail supports the inference more strongly than another available detail.')],
 600)

# ---------------------------------------------------------------- RI.8.1
add('ri81-evidence-informational', 'Strongest Evidence Workshop', 'RI.8.1',
 'Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.',
 'Cite the textual evidence that most strongly supports an analysis of explicit statements and inferences drawn from an informational text.',
 'In informational text, explicit evidence often appears as stated facts, data, or direct quotations from sources. An inference in informational text is a reasonable conclusion drawn from combining facts, not a claim the text states outright. At grade 8, choosing the "strongest" evidence means comparing multiple possible pieces of support and explaining why one is more precise, more directly relevant, or more reliable than another.',
 [('A report states "the bridge was inspected in 2019" and separately "engineers recommended repairs in March 2024 after finding corrosion in support cables." Which detail more strongly supports an inference that the bridge\'s condition worsened over time, and why?',
   'The second detail is stronger, because it directly identifies a specific problem (corrosion) and a specific recommendation for repair, while the first detail alone only establishes a date and says nothing about the bridge\'s condition.'),
  ('If a text states a company\'s profits and separately quotes an employee saying morale was low, which is stronger evidence for an inference about employee experience, and why?',
   'The employee quote is stronger for an inference specifically about employee experience, because it comes from a direct source describing that experience, while profit figures describe financial results and only indirectly relate to how employees felt.')],
 [('Second Chances: How One City Rebuilt Its Public Library System (Part 1)', (
   '1. In 2015, the city of Millbrook faced a decision: renovate its aging central library or close two of its three branches to cut costs. The central library, built in 1962, had not been substantially updated in over fifty years. Its roof leaked in four places, and its basement archive had flooded twice in the previous decade.\n\n'
   '2. City council member Rosa Ibarra argued against closures. "A library is not a luxury," she told the council in a recorded session. "For some families, it is the only place with reliable internet, air conditioning in summer, and a quiet room to study." Her statement was backed by a city survey showing that 38 percent of library visitors used the building for internet access alone.\n\n'
   '3. Opponents of renovation pointed to cost. Estimates from the city engineer placed the renovation at $4.2 million, compared to an estimated $600,000 in annual savings from closing two branches. At that rate, opponents argued, renovation would take seven years just to break even.\n\n'
   '4. The council commissioned an independent study in 2016. The study found that library usage had actually increased by 22 percent over the previous five years, driven largely by after-school programs and job-search workshops for adults. It also found that the two branches proposed for closure served neighborhoods with the city\'s lowest average household income.')),
  ('Second Chances: How One City Rebuilt Its Public Library System (Part 2)', (
   '5. In 2017, the council voted 5–2 to renovate rather than close branches, funding the project through a mix of municipal bonds and a state library-improvement grant. Construction began in 2018 and was completed in early 2020, just before a period when library usage nationally would shift significantly due to public health measures.\n\n'
   '6. By 2023, three years after renovation, Millbrook\'s library system reported that overall visits across all three branches had risen 41 percent compared to 2015 levels. The after-school program alone served over 900 students that year, more than triple its 2015 enrollment of 280.\n\n'
   '7. Rosa Ibarra, no longer on the council but still a frequent visitor, was asked in a 2023 newspaper interview whether the investment had been worth it. She pointed not to the usage statistics but to a single detail: the renovated building now had four public meeting rooms, all booked solid most weeknights, used by tutoring groups, citizenship-class students, and a monthly repair café where residents fixed broken appliances instead of throwing them away.'))],
 [('What does paragraph 1 state explicitly about the library\'s physical condition before renovation?', 'The roof leaked in four places, and the basement archive had flooded twice in the previous decade.'),
  ('Which piece of evidence most strongly supports the inference that low-income families would be most affected by branch closures, and why is it stronger than other available evidence?', 'The finding in paragraph 4 that the branches proposed for closure served neighborhoods with the city\'s lowest average household income is strongest, because it directly and specifically connects closure to income level, unlike Rosa Ibarra\'s general statement about libraries being important, which does not specify which neighborhoods would be affected.'),
  ('What explicit statistic does the city survey provide about internet access, according to paragraph 2?', '38 percent of library visitors used the building for internet access alone.'),
  ('What is the strongest evidence for an inference that renovation opponents were focused mainly on short-term cost rather than long-term community impact? Explain your choice.', 'The strongest evidence is that opponents calculated renovation would "take seven years just to break even" (paragraph 3), a purely financial comparison; this is stronger than simply noting they opposed renovation, because it shows their argument was built specifically around a break-even cost calculation rather than community outcomes.'),
  ('What explicit finding did the 2016 independent study report about library usage trends?', 'Library usage had increased by 22 percent over the previous five years.'),
  ('Between the 22 percent usage increase and the finding about low-income neighborhoods, which more strongly supports the council\'s eventual decision to renovate rather than close branches? Justify your answer.', 'The finding about low-income neighborhoods is somewhat stronger for justifying renovation specifically over closure, because it identifies a direct equity consequence of closing branches, while the usage increase shows the library was valuable but does not by itself argue against closing the two lower-use branches.'),
  ('What explicit vote result is stated in paragraph 5?', 'The council voted 5–2 to renovate rather than close branches.'),
  ('What can you infer about the timing of the renovation\'s completion from paragraph 5? Cite the strongest evidence.', 'The renovation was completed at a fortunate time, just before increased public reliance on libraries; the strongest evidence is the phrase "just before a period when library usage nationally would shift significantly due to public health measures," which directly signals a timing connection without stating the outcome explicitly.'),
  ('What explicit statistic does paragraph 6 give about overall visit growth by 2023?', 'Overall visits across all three branches had risen 41 percent compared to 2015 levels.'),
  ('Which is stronger evidence that the after-school program specifically drove the increase in usage: the 22 percent five-year increase from 2016, or the tripling of after-school enrollment mentioned in paragraph 6? Explain.', 'The tripling of after-school enrollment (from 280 to over 900 students) is stronger, because it isolates one specific program\'s growth, while the 22 percent figure is a broader usage statistic that could be caused by many different factors, not just after-school programs.'),
  ('What explicit detail does Rosa Ibarra point to in paragraph 7 when asked if the investment was worth it?', 'The four public meeting rooms, booked solid most weeknights with tutoring groups, citizenship-class students, and a repair café.'),
  ('Why might Rosa Ibarra\'s choice to cite meeting-room usage, rather than the 41 percent visit increase, be considered strong evidence of her personal view? Explain using the text.', 'It suggests she values the library\'s role as a community gathering space more than raw visitor numbers; the text explicitly says she "pointed not to the usage statistics but to" the meeting rooms, showing a deliberate choice to emphasize a different kind of evidence than the official statistics.'),
  ('Explain the difference between an explicit fact and an inference using two examples from this article.', 'Explicit: the article directly states the renovation cost $4.2 million (paragraph 3). Inference: a reader must conclude that community programs, not just building repairs, drove the growth in usage, since the article never states this as a single direct claim but supports it with several related facts.'),
  ('A reader claims the article proves renovation was purely a financial success. Using the strongest evidence, explain why this claim oversimplifies the article.', 'The claim oversimplifies the article because the strongest evidence of impact, such as the growth in after-school enrollment and the daily use of meeting rooms, describes community and educational outcomes, not financial ones; the article never presents a direct financial return figure to support a claim of purely financial success.'),
  ('Which piece of evidence in the article is least useful for supporting an inference about community impact, and why?', 'The $4.2 million renovation estimate (paragraph 3) is least useful for that specific inference, because it is a cost figure that describes the investment itself rather than any outcome or effect on the community.'),
  ('Identify one place in the article where two different inferences could reasonably be drawn from the same evidence, and explain both.', 'The 5–2 council vote (paragraph 5) could support either "most council members were convinced by the equity findings" or "two members had unresolved concerns about cost"; both are reasonable, since the article states the vote but does not explain the two dissenting votes.'),
  ('What explicit detail from paragraph 4 identifies which programs drove the usage increase, and why is it stronger evidence than simply citing the 22 percent figure alone?', 'The article explicitly states the increase was "driven largely by after-school programs and job-search workshops for adults"; naming the specific programs is stronger evidence than the 22 percent figure alone, because it explains the cause of the growth rather than just reporting that growth happened.'),
  ('Why does the article include the detail that construction finished "just before" a period of national change in library use? What inference does this support?', 'It supports the inference that Millbrook\'s renovation was fortunately timed, which strengthens the case that the investment paid off, since the newly renovated building was ready right as broader demand for library services likely shifted.'),
  ('Compare the strength of Rosa Ibarra\'s 2015 survey statistic (paragraph 2) to the 2023 enrollment statistic (paragraph 6) as evidence for the renovation\'s long-term success. Which is stronger, and why?', 'The 2023 enrollment statistic is stronger evidence of long-term success, because it measures an actual outcome years after renovation was completed, while the 2015 survey statistic only measured need before the renovation happened and cannot by itself confirm the investment worked.'),
  ('Write one full inference about the value of the renovation to the community, and identify the single strongest piece of evidence that supports it, explaining why it beats at least one other candidate detail.', 'Answers vary; require a clear inference plus one specific cited detail, with an explanation of why that detail supports the inference more strongly than at least one other available detail from the article.')],
 600)
