"""Thirty distinct professional learning contexts with original scripts and cases.
General instructional routines, not individualized treatment or crisis plans.
"""
# title, goal, observable situation, five-step routine, adult script, avoid, activity, home bridge
TOPICS=[
('A Calm Arrival','Start class with a predictable entry sequence','Several students stand at the doorway while bags and papers block the entry route.',
 ['Welcome each learner by name','Point to one visible first task','Put materials in a marked place','Offer two ways to begin','Check in privately after the group starts'],
 'You are here. Put your things in your space, then choose the first step you can start.',
 'Calling out late arrivals in front of classmates. A public reprimand does not teach the entry sequence.',
 'Rehearse the route from doorway to storage to first task. Partners check that the path stays clear and the task can be found without asking.',
 'Choose a predictable place for tomorrow’s materials. Let the child check one item before an adult checks the rest.'),
('Directions Students Can Use','Make the next action visible and check understanding','After a four-part oral direction, students begin different tasks and repeatedly ask what to do.',
 ['State one action in plain language','Show the matching example','Ask a learner to explain the action','Allow a brief start interval','Add the next step after checking'],
 'The first action is ___. Show or tell me what you will do first; then we will add the next step.',
 'Asking only “Does everyone understand?” Agreement does not show what students understood.',
 'Give pairs a short classroom task. One partner writes three directions; the other follows them literally, then they revise ambiguous words.',
 'Give one household direction at a time. Ask the child to point to the needed object or tell the first action.'),
('Transitions with a Destination','Teach a clear route between activities','Students finish one activity but wander while the next materials are being prepared.',
 ['Name the next place and task','Explain where current materials go','Model one safe route','Rehearse the route without rushing','Notice one successful transition step'],
 'We are moving from ___ to ___. Carry ___, leave ___, and begin ___ when you arrive.',
 'Making speed the only success measure. A fast transition can still leave students confused or materials unsafe.',
 'Draw a before-and-after map of two learning areas. Students identify a clear walking path and practice the arrival task at the destination.',
 'Preview the next activity and what stays behind. Offer a simple transition choice, such as carrying the book or the pencil case.'),
('Materials with a Home','Create a usable system for shared materials','Students search several containers and interrupt classmates to find common supplies.',
 ['Name each supply location','Label with a word and example','Assign a simple collection route','Practice borrowing and returning','Check the system at cleanup'],
 'The label tells us where this belongs. Try that location first; if it is empty, use the help signal.',
 'Assuming a messy container shows laziness. The system may be unclear or hard to reach.',
 'Invite small groups to sort a small set of classroom supplies in two ways. Choose the arrangement that a new learner can explain most easily.',
 'Set up one small supply station. Ask the child to choose a label and teach an adult how to find and return an item.'),
('Asking for Help with Confidence','Make help-seeking specific and accessible','A student waits silently for much of independent work after getting stuck on the first item.',
 ['Teach an accessible help signal','Name the exact point of confusion','Try one available support','Ask a person with a specific question','Return to one manageable step'],
 'Show me the last step that made sense. We can choose a model, a prompt, or a short explanation together.',
 'Requiring a student to try three strategies before any help, even when access or comprehension is already a barrier.',
 'Pairs compare vague help requests with specific ones. They rewrite “I do not get it” as a question about a word, direction, or operation.',
 'Use “Show me where you got stuck” during homework or a household task. Praise the specific request, not speed.'),
('Partners Who Both Participate','Structure partner work so each learner contributes','One partner completes the page while the other watches and copies.',
 ['Assign a first speaker and listener','Give each partner a short thinking turn','Require a question before agreement','Switch roles after one item','Record both contributions'],
 'Each person will explain one part. Listening includes a question that helps your partner make the reasoning clearer.',
 'Using the stronger reader as a permanent tutor. Fixed roles can hide the other learner’s thinking.',
 'Use two methods for the same simple task. Partner A describes a method, Partner B restates and questions it, then roles reverse.',
 'Take turns explaining how to complete a familiar activity. The listener asks one question before offering advice.'),
('Group Roles That Rotate','Give group members meaningful and changeable responsibilities','The same student manages every project while other members wait for instructions.',
 ['Name the shared product','Choose roles tied to real actions','Set a short role-rotation point','Check every voice before deciding','Review how roles helped the task'],
 'A role is a job for this round, not a label for a person. We will rotate so everyone practices each action.',
 'Giving a decorative role with no influence on the work, or assigning roles according to a fixed ability label.',
 'Groups build a plan for a classroom display. Use organizer, evidence checker, questioner, and reporter roles, then rotate during a second round.',
 'Rotate small planning roles during a shared family task. Let each person make one real decision.'),
('Listening with Visible Evidence','Help students show listening without requiring one body posture','A speaker finishes and classmates respond without referring to the idea that was shared.',
 ['Offer several ways to attend','Name one idea to listen for','Allow thinking time','Restate before responding','Check the speaker’s meaning'],
 'You can look at the speaker, the notes, or your own organizer. Be ready to name one idea you heard.',
 'Treating eye contact or stillness as the only proof of attention.',
 'In groups of three, a speaker describes a choice, a listener restates it, and an observer notes whether the restatement matches. Rotate all roles.',
 'After a child shares an idea, restate it and ask whether you understood. Invite the child to do the same for an adult.'),
('Discussion without a Rush','Build discussion turns that include thinking time','A few students answer every question before other learners have time to prepare.',
 ['Pose one clear question','Offer silent or drawn thinking time','Invite a low-pressure rehearsal','Use an equitable turn structure','Connect ideas before moving on'],
 'Take a moment to write, draw, or think. You may share your idea, ask a question, or pass for now and return later.',
 'Calling on an unprepared student as punishment for not speaking.',
 'Use a low-stakes classroom choice question. Students prepare an idea, rehearse with a partner, then connect or question an idea in the group.',
 'Ask an open question and allow silence. Offer drawing or showing an example when speaking immediately is difficult.'),
('Feedback That Gives a Next Step','Make feedback usable during revision','A learner receives “good job” or “try harder” but cannot identify what to change.',
 ['Name the goal','Point to one piece of evidence','Describe one specific next action','Provide time to try it','Check the revised evidence'],
 'This part already shows ___. Your next action is ___. Try it here, and we will compare the change.',
 'Giving a long list of corrections without time to use them.',
 'Compare three sample feedback statements for a simple drawing or explanation. Sort by whether a learner can act on the feedback immediately.',
 'Describe a successful action, then offer one small next step. Give the child a chance to try it before adding another suggestion.'),
('Mistakes as Information','Use errors to locate a teachable step','A student erases an entire response after one correction and says the whole task is wrong.',
 ['Preserve the useful work','Locate the first unclear step','Compare with a model','Revise one part','Explain what the change fixed'],
 'Keep the part that works. Let us find the first step that needs another look.',
 'Displaying an identifiable student error without permission or treating mistakes as a competition.',
 'Use an invented flawed set of directions. Pairs identify the first problem, revise it, and explain why the corrected step helps.',
 'When a task goes wrong, name the part that worked and one part to adjust. Model an adult making and fixing a small mistake.'),
('A First Step for Starting Work','Reduce uncertainty at the beginning of a task','A learner spends the first ten minutes moving supplies without beginning the assignment.',
 ['Check access to directions and tools','Identify the smallest meaningful action','Offer a bounded start choice','Work alongside briefly if needed','Review the first completed step'],
 'Would you like to start by labeling the model or reading the first direction with me?',
 'Assuming delayed starting is defiance before checking understanding, workload, or missing materials.',
 'Give groups three complex classroom tasks. They identify a first action that takes under two minutes and still moves toward the real goal.',
 'Agree on one small starting action for a home task. Offer companionship at the start without completing the task for the child.'),
('Pacing with Checkpoints','Help learners plan a work period in manageable portions','A student completes a large section quickly with missing steps, while another works carefully but never reaches the final part.',
 ['Preview the whole task','Identify two meaningful checkpoints','Estimate a flexible work interval','Pause to compare progress and understanding','Adjust the next portion'],
 'Our checkpoint is after ___. We are checking the work and the plan, not racing one another.',
 'Turning a timer into a public countdown that removes needed processing time.',
 'Students break a small project into three parts, estimate each part, then compare estimates with experience and revise the plan.',
 'Plan a household task with a pause point. Discuss what took more effort than expected and adjust the next plan.'),
('Meaningful Work after Finishing','Provide extensions that deepen an already completed task','Early finishers receive unrelated extra pages and begin rushing their original work.',
 ['Check the original goal first','Offer two related extension choices','Ask for deeper reasoning or transfer','Set a clear stopping point','Share one new insight'],
 'Before extending, check the original work. Then choose a second method or a new example that stretches the same idea.',
 'Using extra repetitive work as a reward for completing work accurately.',
 'Create an extension menu for a familiar lesson: explain a second method, design a counterexample, make a teaching example, or apply the idea elsewhere.',
 'When a task is complete, invite a useful choice: explain the method, improve one part, or help plan the next activity.'),
('Finishing Unfinished Work','Plan completion without turning backlog into punishment','A learner carries several unfinished pages between school and home without knowing which matter most.',
 ['Identify the essential learning evidence','Separate missing work from unclear learning','Choose one priority task','Schedule a realistic next opportunity','Review progress privately'],
 'We will decide which part best shows the learning goal. Let us make a plan for that part first.',
 'Automatically removing every break or preferred activity until all old work is complete.',
 'Use an invented backlog of four tasks. Learners rank what needs clarification, what can be shortened, and what should be completed first, with reasons.',
 'Ask which task is the agreed priority. Help prepare a work space and communicate obstacles without adding a second punishment.'),
('Organization Learners Can Explain','Design a simple system for finding and submitting work','Completed work stays in a backpack because the learner does not remember the submission process.',
 ['Choose one collection location','Label current and completed work','Model a real example','Practice retrieval and submission','Review the system with the learner'],
 'Show me where work goes when you start and where it goes when you finish. We can simplify any confusing step.',
 'Adding many color codes, folders, and checklists at once without teaching how they connect.',
 'Partners test a two-location paper system using sample papers. One partner explains it to someone who did not help design it.',
 'Use one place for school messages and one for work to return. Let the child explain the system in their own words.'),
('A Welcoming Return after Absence','Support re-entry with clear priorities and belonging','A returning learner receives a stack of missed work before anyone explains the current lesson.',
 ['Welcome without public questions','Explain the current learning goal','Identify essential missed information','Agree on one manageable catch-up step','Check in privately later'],
 'We are glad you are here. Today we are working on ___. This one example will help you join us.',
 'Requiring a student to explain personal absence details to classmates.',
 'Build a one-page welcome-back map containing today’s goal, a worked example, a partner contact, and the first catch-up priority.',
 'Ask the school which missed learning is essential. Help the child identify one current task before tackling a whole backlog.'),
('Homework with a Clear Purpose','Make home practice understandable and limited in scope','Families cannot tell whether an assignment is practice, a new lesson, or a project requiring adult teaching.',
 ['State the purpose in one sentence','Demonstrate a representative item','Name expected independent effort','Explain how to signal difficulty','Use returned work to plan teaching'],
 'This practices ___. Try the example first. If you are stuck, mark the exact point and bring that question back.',
 'Treating access to quiet space, devices, or adult help as evidence of student effort.',
 'Rewrite a sample homework direction to include purpose, materials, an example, and what to do when stuck. Check that it can be used without a paid app.',
 'Ask the child to explain the example. If the work is inaccessible, note the barrier and contact the teacher rather than teaching a conflicting method.'),
('Reading Time with Stamina and Choice','Plan reading participation with accessible texts and a clear purpose','During independent reading, students change books repeatedly because the text or purpose is unclear.',
 ['Offer accessible text choices','Name a small reading purpose','Set a flexible reading interval','Use a quick response option','Adjust text or support from evidence'],
 'Choose a text you can enter today. Read or listen for one detail you can explain, then tell, draw, or note it.',
 'Measuring reading engagement only by silence, page count, or an unverified reading-level label.',
 'Create a reading-choice conference using topic interest, text access, and a response option. Students explain why a text is workable for the current purpose.',
 'Share a short reading or listening time. Invite a detail or question rather than testing every unfamiliar word.'),
('Revision with a Purpose','Help learners improve meaning before polishing every surface feature','A writer recopies a draft neatly without changing unclear ideas.',
 ['Name the reader’s need','Choose one revision target','Locate a specific place to change','Try an alternative','Compare the versions against the goal'],
 'Your reader needs to understand ___. Which sentence or detail could make that clearer?',
 'Treating revision as a requirement to make writing longer or correcting every feature at once.',
 'Use a short invented classroom announcement. Teams revise it for a new student who does not know the routine, then compare which changes aid meaning.',
 'Ask the child what they want the reader to understand. Respond as a reader before editing spelling or handwriting.'),
('Math Talk beyond the Answer','Make mathematical reasoning visible through several representations','Students state numerical answers but cannot connect the operation to the situation.',
 ['Ask what the quantities mean','Invite a model or diagram','Connect the model with an equation','Compare two methods','Check the result in context'],
 'What does this number count? Show how your model and equation describe the same situation.',
 'Equating speed with mathematical understanding or insisting on one method when several are valid.',
 'Use a simple equal-sharing situation. Each group represents it with objects, a drawing, and words, then explains how the representations connect.',
 'Ask how the child knows an answer fits a real situation. Accept a drawing or objects before asking for formal notation.'),
('Project Materials and Careful Setup','Teach preparation and cleanup for ordinary classroom projects','Groups begin cutting and arranging materials before checking the instructions or shared workspace.',
 ['Review school-approved activity directions','Identify needed materials only','Assign a clear workspace','Check readiness before starting','Restore and account for supplies'],
 'Before we begin, show the materials list and the workspace plan. We will use only the tools approved for this activity.',
 'Substituting a general classroom checklist for required laboratory, tool, or school safety instruction.',
 'Plan a paper-only design task. Groups make a materials list, sketch their workspace, and rehearse cleanup before using supplies.',
 'For an ordinary paper project, gather only the needed materials and agree on cleanup. Adults select age-appropriate tools and supervision.'),
('Digital Focus with a Defined Task','Keep device use connected to a visible learning purpose','Learners open several unrelated tabs because the digital task has no clear completion point.',
 ['State the learning product','Open only the needed resource','Use an agreed help signal','Pause to show evidence of progress','Close or submit with a final check'],
 'The device is helping us create ___. Show the next step in that task, and ask if a link or tool is unclear.',
 'Making access to personal devices, paid software, or public accounts a requirement when an accessible alternative is needed.',
 'Compare a paper and digital route to the same learning product. Students list where a device helps and where it adds unnecessary steps.',
 'Agree on the task and a check-in point before starting. Keep a paper alternative available when school access fails.'),
('Shared Devices, Shared Thinking','Structure turns on one device without sidelining partners','One learner controls the keyboard while the partner contributes little to the decision-making.',
 ['Assign operator and navigator roles','Require a spoken plan before clicking','Switch after one meaningful step','Record both learners’ reasoning','Review the shared result together'],
 'The navigator explains the next action; the operator carries it out. Then switch so each person practices both jobs.',
 'Allowing keyboard speed to determine who controls every turn.',
 'Use an offline slideshow or shared paper prototype. One learner describes an edit, the other performs it, and both explain why it serves the goal.',
 'Take turns planning and carrying out a simple device task. Let each person explain the next action before changing roles.'),
('Movement with a Learning Purpose','Offer movement options that preserve access and clear routines','Some learners need to move during extended work, but the room has no agreed way to do so.',
 ['Identify available space and access needs','Offer a seated and moving option','Model the start and return cues','Practice without speed or competition','Review whether the option helps learning'],
 'Choose the movement or seated option that works for you. When you return, your next learning step is ___.',
 'Withholding necessary movement or access supports as a consequence for unfinished work.',
 'Design two ways to respond to the same sorting task: moving a card to a station or sorting cards at a desk. Compare whether both show the same learning.',
 'Offer a brief movement or seated pause during a long task. Agree on how to return to one clear next step.'),
('A Calm Space with a Return Plan','Create a voluntary regulation space that supports rejoining','A quiet corner exists, but learners are unsure when to use it or how to return to instruction.',
 ['Explain the voluntary purpose','Offer accessible quiet options','Keep adult support available','Plan one ready-to-return signal','Reconnect with a manageable learning step'],
 'You may use a quiet option. I will check in, and when you are ready we can choose the first step back.',
 'Using the space for isolation, punishment, forced time limits, or withholding supervision.',
 'Students evaluate a fictional quiet-space plan for access, privacy, supervision, and a return route. They revise it using neutral, respectful language.',
 'Choose a voluntary quiet option at home and remain available. When ready, reconnect before discussing the next task.'),
('Disagreement with a Repair Route','Teach respectful disagreement and practical repair','Two learners argue about a shared decision and stop listening to each other’s reasons.',
 ['Pause the disputed task','Hear each account separately if needed','Name the shared problem neutrally','Offer safe, realistic next options','Check whether the agreement worked'],
 'I hear two different views. Let us name what each person needs for the next step without deciding who is a bad person.',
 'Forcing apologies, mediation, or equal blame when there is a safety concern, bullying, or a power imbalance; follow school procedures instead.',
 'Use a fictional disagreement about display space. Teams generate two workable options and check whether each person can participate.',
 'Listen to the child’s account without assigning motives. Help name a practical next request; involve the school when safety or repeated harm is involved.'),
('A Substitute Day Students Understand','Prepare a class for continuity when the usual teacher is away','Students repeatedly ask which routines still apply when a substitute leads the class.',
 ['Post the familiar class sequence','Name routines that remain available','Identify where to ask for help','Use a manageable independent task','Leave a factual handover note'],
 'Our familiar routines still help us today. The plan shows the next task and who can help if something is unclear.',
 'Asking a student to manage peers or disclose confidential learner information to the class.',
 'Create a student-facing one-page day map and a separate adult handover list. Sort information according to whether students or the authorized adult need it.',
 'Ask what routine helped the child during a change in teacher. Reinforce the agreed help route without asking the child to supervise classmates.'),
('Family Messages That Invite Partnership','Write clear, respectful messages with a shared next step','A family receives a message about a problem without an example or an action they can discuss.',
 ['Start with a neutral observation','Describe the learning impact','Ask for family perspective','Offer one manageable shared action','Set a follow-up point'],
 'I noticed ___ during ___. What are you seeing at home? Could we try ___ and compare what we notice next week?',
 'Including private information about other children, making diagnoses, or sending blame-focused messages.',
 'Rewrite a fictional blame-focused note into a short partnership message with one observation, one question, and one next step.',
 'Reply with a specific observation and question. Ask which action matters most so school and home are not using conflicting plans.'),
('Student Voice in Classroom Routines','Invite learners to improve routines using observable evidence','Adults repeatedly revise a classroom system without asking the students who use it.',
 ['Identify one routine to study','Offer several feedback formats','Look for recurring access barriers','Choose one realistic change together','Review evidence after trying it'],
 'Which step helps you participate, and which step gets in the way? You can tell, draw, or write your suggestion.',
 'Promising that every suggestion will be adopted or collecting feedback without explaining the decision.',
 'Run a small routine-design cycle: notice, suggest, select, try, and review. Students identify what evidence would show that the change helps.',
 'Invite the child to suggest one improvement to a home routine. Explain which parts can change and review the trial together.'),
]
assert len(TOPICS)==30
