import {collectionsFor,gradesFor} from '../lib/catalog-filters';
import { env } from 'cloudflare:workers';
import { body, customer, db, hasOriginalListing, originalListing, initialize, json, mutation, owner, publicCatalog, StoreError } from './commerce';
import { defaultSite } from '../lib/editor-defaults';
type DocumentRow={id:string;draft:string;live:string|null;previous:string|null;revision:number;published_revision:number;updated_at:string};
type FileRow={id:string;product_id:string;kind:string;storage_key:string;name:string;content_type:string;bytes:number};
const bucket=()=>{const b=Reflect.get(env,'PAID_FILES') as R2Bucket|undefined;if(!b)throw new StoreError(503,'File storage is unavailable.');return b;};
export async function requireEditor(request:Request){const u=await customer(request);if(!owner(u))throw new StoreError(403,'Only the store owner can edit this website.');return u;}
const validId=(id:unknown)=>typeof id==='string'&&/^[a-z0-9][a-z0-9-]{1,99}$/.test(id);
const text=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const strings=(v:unknown)=>Array.isArray(v)?v.slice(0,80).map(x=>text(x,300)).filter(Boolean):[];
function link(v:unknown){const s=text(v,1000);if(!s)return '';if(/^\/(?!\/)[^\\\s]*$/.test(s))return s;throw new StoreError(422,'Use a website path beginning with / for links.');}
function validate(input:any,site:boolean){
 if(!input||typeof input!=='object'||Array.isArray(input))throw new StoreError(422,'Invalid draft.');
 if(site)return {...defaultSite,...Object.fromEntries(['heroTitle','heroAccent','heroText','buttonLabel','seoTitle','seoDescription','supportText','licenseText','samplerTitle','samplerFile'].map(k=>[k,text(input[k])])),buttonUrl:link(input.buttonUrl)||'/#shop',navigation:(Array.isArray(input.navigation)?input.navigation:defaultSite.navigation).slice(0,12).map((n:any)=>({label:text(n.label,40),url:link(n.url)})).filter((n:any)=>n.label&&n.url),collections:(Array.isArray(input.collections)?input.collections:[]).slice(0,80).map((c:any)=>({title:text(c.title,80),description:text(c.description,300)})).filter((c:any)=>c.title)};
 const output:any={};
 for(const k of ['title','level','subject','standard','description','resourceType','minutes','source','detailedDescription','audience','answerKey','license','requiredBook','seoTitle','seoDescription','thumbnailAlt','previewDescription','objective','preparation','teacherUse','studentDirections'])output[k]=text(input[k],k==='title'?180:5000);
 for(const k of ['formats','included','collections','grades','states','tags','relatedProducts','bundleProducts'])output[k]=strings(input[k]);
 for(const k of ['pages','slides'])output[k]=Math.max(0,Math.min(10000,Math.floor(Number(input[k])||0)));
 output.priceCents=Number(input.priceCents);if(!Number.isInteger(output.priceCents)||output.priceCents<1||output.priceCents>100000)throw new StoreError(422,'Enter a price from $0.01 to $1,000.00.');
 for(const k of ['paidFile','coverFile'])output[k]=text(input[k],100);
 output.sampleFiles=strings(input.sampleFiles);output.approved=input.approved===true;
 if(!output.states.length)output.states=output.level.split('•').slice(1).map((v:string)=>v.trim()).filter(Boolean);
 if(!output.grades.length)output.grades=[output.level.split('•')[0].trim()].filter(Boolean);
 if(!output.title)throw new StoreError(422,'A product title is required.');
 return output;
}
export async function siteContent(){const row=await db().prepare("SELECT live FROM editor_documents WHERE id='site'").first<{live:string|null}>();return {...defaultSite,...(row?.live?JSON.parse(row.live):{})};}
export async function editorGet(request:Request){await requireEditor(request);await initialize();const products=await publicCatalog();const {results:raw}=await db().prepare('SELECT id,title,price_cents,metadata,approved,ready FROM store_products').all<any>();const {results:docs}=await db().prepare('SELECT * FROM editor_documents').all<DocumentRow>();const {results:files}=await db().prepare('SELECT id,product_id,kind,name,content_type,bytes FROM editor_files ORDER BY created_at DESC').all();return json({products:raw.map(p=>({...JSON.parse(p.metadata),...products.find(x=>x.id===p.id),id:p.id,title:p.title,priceCents:p.price_cents,approved:!!p.approved,ready:!!p.ready,collections:collectionsFor({...JSON.parse(p.metadata),...products.find(x=>x.id===p.id)}),grades:gradesFor({...JSON.parse(p.metadata),...products.find(x=>x.id===p.id)})})),documents:docs.map(d=>({...d,draft:JSON.parse(d.draft),live:d.live?JSON.parse(d.live):null,previous:d.previous?JSON.parse(d.previous):null})),files,site:await siteContent()});}
export async function editorSave(request:Request){mutation(request);await requireEditor(request);const input=await body(request),id=input.id;if(id!=='site'&&!validId(id))throw new StoreError(422,'Use a product URL with lowercase letters, numbers, and hyphens.');const revision=Number(input.revision);if(!Number.isInteger(revision)||revision<0)throw new StoreError(422,'Invalid draft version.');const draft=validate(input.draft,id==='site');const existing=await db().prepare('SELECT * FROM editor_documents WHERE id=?').bind(id).first<DocumentRow>();if(existing?.revision!==revision&&!(revision===0&&!existing))throw new StoreError(409,'This draft changed in another window. Reload the editor before saving.');
 const encoded=JSON.stringify(draft),now=new Date().toISOString();const result=existing?await db().prepare('UPDATE editor_documents SET draft=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(encoded,now,id,revision).run():await db().prepare('INSERT OR IGNORE INTO editor_documents(id,draft,revision,updated_at) VALUES(?,?,1,?)').bind(id,encoded,now).run();if(!result.meta.changes)throw new StoreError(409,'This draft changed in another window. Reload the editor.');return json({revision:revision+1,draft});}
async function fileFor(id:string,productId:string,kind:string){const f=await db().prepare('SELECT * FROM editor_files WHERE id=? AND product_id=? AND kind=?').bind(id,productId,kind).first<FileRow>();if(!f||!(await bucket().head(f.storage_key)))throw new StoreError(422,'An attached file is missing. Please upload it again.');return f;}
export async function editorPublish(request:Request){mutation(request);await requireEditor(request);const input=await body(request),id=input.id;const row=await db().prepare('SELECT * FROM editor_documents WHERE id=?').bind(id).first<DocumentRow>();if(!row||row.revision!==input.revision)throw new StoreError(409,'Save your latest draft before publishing.');const draft=validate(JSON.parse(row.draft),id==='site');
 const publish=db().prepare('UPDATE editor_documents SET previous=live,live=draft,published_revision=revision,updated_at=? WHERE id=? AND revision=?').bind(new Date().toISOString(),id,row.revision);
 if(id==='site'){if(draft.samplerFile)await fileFor(draft.samplerFile,'site','sampler');const r=await publish.run();if(!r.meta.changes)throw new StoreError(409,'The draft changed. Review it again.');return json({published:true});}
 const current=await db().prepare('SELECT * FROM store_products WHERE id=?').bind(id).first<any>();let storageKey=current?.storage_key||'',ready=!!current?.ready;
 if(draft.paidFile){const f=await fileFor(draft.paidFile,id,'paid');storageKey=f.storage_key;ready=true;}
 const existingPublic=(await publicCatalog()).find(p=>p.id===id);
 const metadata={...(current?JSON.parse(current.metadata):{}),...existingPublic,...draft,editorManaged:true,id};
 if(current&&JSON.parse(current.metadata).editorManaged){const original=originalListing(id);delete metadata.thumbnailSrc;if(original?.previews)metadata.previews=original.previews;else delete metadata.previews;}
 if(draft.coverFile){await fileFor(draft.coverFile,id,'cover');metadata.thumbnailSrc='/api/editor/media?id='+draft.coverFile;}
 if(draft.sampleFiles.length){for(const f of draft.sampleFiles)await fileFor(f,id,'sample');metadata.previews=draft.sampleFiles.map((f:string,i:number)=>({src:'/api/editor/media?id='+f,alt:`Sample ${i+1} from ${draft.title}`}));}
 if(draft.approved&&(!ready||!draft.description||!draft.subject||!draft.level||!draft.formats.length||!draft.included.length||(!metadata.thumbnailSrc&&!hasOriginalListing(id))||(!metadata.previews&&!hasOriginalListing(id))))throw new StoreError(422,'Before listing for sale, add a file, cover, sample, description, grade, subject, formats, and included contents.');
 for(const ref of [...draft.relatedProducts,...draft.bundleProducts]){if(ref===id||!await db().prepare('SELECT id FROM store_products WHERE id=? AND approved=1').bind(ref).first())throw new StoreError(422,'Choose existing published products for related resources and bundles.');}
 // Both statements use the saved revision. A concurrent save cannot publish stale pricing or files.
 const update=db().prepare(`INSERT INTO store_products(id,title,price_cents,approved,metadata,storage_key,ready) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM editor_documents WHERE id=? AND revision=?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,price_cents=excluded.price_cents,approved=excluded.approved,metadata=excluded.metadata,storage_key=excluded.storage_key,ready=excluded.ready`).bind(id,draft.title,draft.priceCents,draft.approved?1:0,JSON.stringify(metadata),storageKey,ready?1:0,id,row.revision);
 const results=await db().batch([update,publish]);if(!results[1].meta.changes)throw new StoreError(409,'The draft changed. Review it again.');return json({published:true});}
export async function editorUpload(request:Request){mutation(request);await requireEditor(request);const u=new URL(request.url),productId=u.searchParams.get('productId')||'',kind=u.searchParams.get('kind')||'',name=text(u.searchParams.get('name'),180).replace(/[^a-zA-Z0-9._ -]/g,'_');if((productId!=='site'&&!validId(productId))||!['paid','cover','sample','sampler'].includes(kind))throw new StoreError(422,'Invalid upload destination.');const ext=name.split('.').pop()?.toLowerCase()||'';const types:Record<string,string>={pdf:'application/pdf',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',zip:'application/zip',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'};if(!types[ext]||(['cover','sample'].includes(kind)?!['png','jpg','jpeg','webp'].includes(ext):kind==='sampler'?ext!=='pdf':!['pdf','pptx','zip'].includes(ext)))throw new StoreError(422,'Choose the file type shown beside this upload.');
 const max=['cover','sample'].includes(kind)?8*1024*1024:30*1024*1024;if(Number(request.headers.get('content-length')||0)>max)throw new StoreError(413,'File is too large.');const reader=request.body?.getReader();if(!reader)throw new StoreError(422,'Choose a file.');const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new StoreError(413,'File is too large. Maximum 30 MB for documents or 8 MB for images.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}
 const signature=Array.from(bytes.slice(0,12)),ascii=new TextDecoder().decode(bytes.slice(0,12));const valid=ext==='pdf'?ascii.startsWith('%PDF-'):['pptx','zip'].includes(ext)?signature[0]===80&&signature[1]===75&&signature[2]===3&&signature[3]===4:ext==='png'?signature.slice(0,8).join(',')==='137,80,78,71,13,10,26,10':['jpg','jpeg'].includes(ext)?signature[0]===255&&signature[1]===216&&signature[2]===255:ascii.startsWith('RIFF')&&ascii.slice(8)==='WEBP';if(!valid)throw new StoreError(422,'This file does not match its extension. Export it again before uploading.');
 const id=crypto.randomUUID(),key=`editor/${productId}/${id}.${ext}`;await bucket().put(key,bytes,{httpMetadata:{contentType:types[ext]}});const stored=await bucket().head(key);if(!stored||stored.size!==size)throw new StoreError(503,'Upload could not be verified. Try again.');await db().prepare('INSERT INTO editor_files(id,product_id,kind,storage_key,name,content_type,bytes,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,productId,kind,key,name,types[ext],size,new Date().toISOString()).run();return json({id,product_id:productId,kind,name,content_type:types[ext],bytes:size});}
export async function editorMedia(request:Request){const u=new URL(request.url),id=u.searchParams.get('id')||'';const f=await db().prepare('SELECT * FROM editor_files WHERE id=?').bind(id).first<FileRow>();if(!f)throw new StoreError(404,'File not found.');let allowed=false;
 if(f.kind!=='paid'){const d=await db().prepare('SELECT live FROM editor_documents WHERE id=?').bind(f.product_id).first<{live:string|null}>();const live=d?.live?JSON.parse(d.live):{};allowed=f.product_id==='site'?live.samplerFile===id:live.approved===true&&(live.coverFile===id||live.sampleFiles?.includes(id));}
 if(!allowed)await requireEditor(request);const file=await bucket().get(f.storage_key);if(!file)throw new StoreError(404,'File not found.');return new Response(file.body,{headers:{'Content-Type':f.content_type,'Content-Disposition':`${f.content_type.startsWith('image/')?'inline':'attachment'}; filename="${f.name}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
