from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.utils import ImageReader
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
import json, shutil

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output/private-drafts/2026-09-14'; RENDER=ROOT/'output/rendered/2026-09-14'
OUT.mkdir(parents=True,exist_ok=True); RENDER.mkdir(parents=True,exist_ok=True)
LOGO=ROOT/'public/brand/saint-pierre-logo.png'
NC_SOURCE='North Carolina Department of Public Instruction, Mathematics Standards Vertical Progression: https://www.dpi.nc.gov/documents/publications/catalog/ma196-vertical-progression-math/open; NC Check-Ins 2.0 Mathematics Specifications: https://www.dpi.nc.gov/documents/accountability/testing/nc-checkin/nc-check-ins-20-mathematics-grades-3-8-specifications (accessed September 14, 2026).'

P=[
dict(slug='nc-g3-two-step-task-cards',title='Two-Step Story Problem Task Cards',level='Grade 3',state='North Carolina',subject='Mathematics',rtype='Task Cards',standard='NC.3.OA.8 - Solve two-step word problems using addition, subtraction, and multiplication, representing problems with equations containing a symbol for the unknown.',source=NC_SOURCE,price='$5.00',time='35-45 minutes',focus='Solve and represent two-step problems, then check whether answers are reasonable.',qs=[('A class packs 6 boxes with 8 markers each, then gives away 15 markers. How many remain?','33'),('Mia reads 24 pages Monday and 18 Tuesday. Her book has 70 pages. How many remain?','28'),('Four teams collect 9 cans each and then collect 17 more. Total?','53'),('A garden has 63 plants in 7 equal rows. Three plants in each row bloom. How many bloom?','21'),('A store had 85 notebooks, sold 29, then received 40. How many now?','96'),('Five buses carry 7 students each. Twelve more arrive by car. Total?','47'),('Write an equation for 9 bags of 4 apples with 11 apples eaten.','9 x 4 - 11 = 25'),('A player earns 8 points in each of 3 rounds and loses 5 penalty points. Score?','19'),('Lena has $50, buys two games at $14 each. Money left?','$22'),('A baker makes 72 rolls, places 8 on each tray, and sells 4 trays. Rolls sold?','32'),('Choose the first operation: 6 shelves hold 5 books each; 9 are borrowed.','Multiply 6 x 5'),('Explain how to check 7 x 6 + 18 = 60.','42 + 18 = 60; reverse with 60 - 18 = 42'),('Create a two-step problem with answer 26.','Answers vary; both operations and equation required.'),('A student says 4 x 9 - 7 = 29. Is the student correct?','Yes; 36 - 7 = 29'),('Estimate whether 8 x 6 + 13 could equal 90.','No; 48 + 13 = 61'),('Represent: 45 stickers shared among 5 students, then each gets 2 more.','45 / 5 + 2 = 11')]),
dict(slug='nc-g5-multiplication-warmups',title='Multi-Digit Multiplication Warm-Up Week',level='Grade 5',state='North Carolina',subject='Mathematics',rtype='Warm-Ups',standard='NC.5.NBT.5 - Demonstrate fluency with multiplication of whole numbers up to three digits by two digits using the standard algorithm.',source=NC_SOURCE,price='$5.00',time='Five 10-minute warm-ups',focus='Build accurate, fluent standard-algorithm multiplication with estimation and error analysis.',qs=[('34 x 26','884'),('128 x 14','1,792'),('305 x 22','6,710'),('Estimate 247 x 31 using compatible numbers.','About 7,500'),('46 x 19','874'),('215 x 43','9,245'),('A printer makes 125 pages per minute for 24 minutes.','3,000 pages'),('Find the error: 63 x 27 = 1,071.','Missing tens-place value; correct product 1,701'),('408 x 16','6,528'),('72 x 35','2,520'),('Which is reasonable for 296 x 18: 532, 5,328, or 53,280?','5,328'),('A theater has 36 rows of 128 seats.','4,608 seats'),('504 x 29','14,616'),('99 x 47','4,653'),('Use a second method to check 214 x 32.','6,848; e.g., 214 x 30 + 214 x 2'),('Explain why the second partial product shifts one place.','It represents multiplication by tens, not ones.')]),
dict(slug='nc-g6-rates-small-group',title='Rates and Percent Small-Group Lab',level='Grade 6',state='North Carolina',subject='Mathematics',rtype='Small-Group Work',standard='NC.6.RP.3 - Use ratio and rate reasoning to solve real-world and mathematical problems, including unit rates and percentages.',source=NC_SOURCE,price='$6.00',time='45-55 minutes',focus='Use tables, unit rates, and percentages to compare situations and justify decisions.',qs=[('3 notebooks cost $7.50. Unit price?','$2.50'),('A car travels 180 miles in 3 hours. Unit rate?','60 mph'),('Complete equivalent ratio 4:7 = 12:__.','21'),('25% of 80','20'),('A $40 item is discounted 15%. Discount amount?','$6'),('A recipe uses 2 cups for 5 servings. Cups per serving?','0.4 cup'),('Which is cheaper: 6 pens for $9 or 10 for $16?','6 for $9; $1.50 each vs. $1.60'),('18 is what percent of 60?','30%'),('Increase 50 by 12%.','56'),('A map scale is 1 inch:8 miles. 3.5 inches represents?','28 miles'),('A runner completes 5 km in 25 min. Minutes per km?','5'),('Explain why 0.35 and 35% are equivalent.','Percent means per hundred; 35/100 = 0.35'),('Create a ratio table for 4 tickets costing $30.','1:$7.50, 2:$15, 4:$30'),('A class of 24 has 18 present. Percent present?','75%'),('Tax is 7% on $60. Total?','$64.20'),('Compare 7/10, 68%, and 0.72.','68% < 7/10 < 0.72')]),
dict(slug='nc-g8-linear-models-homework',title='Linear Models Homework and Exit Ticket',level='Grade 8',state='North Carolina',subject='Mathematics',rtype='Homework',standard='NC.8.F.4 - Analyze functions that model linear relationships; determine and interpret rate of change and initial value from two values or from a graph, table, or description.',source=NC_SOURCE,price='$6.00',time='40-50 minutes',focus='Build linear models from tables and contexts and interpret slope and initial value with units.',qs=[('Find slope through (2,7) and (6,19).','3'),('Write y=mx+b when m=4 and b=-2.','y=4x-2'),('Table: x 0,2,4; y 5,11,17. Find m and b.','m=3, b=5'),('A taxi charges $4 plus $2.50 per mile. Model.','C=2.5m+4'),('Interpret 4 in the taxi model.','$4 initial fee'),('Find taxi cost for 8 miles.','$24'),('Line through (3,10) with slope 2. Find b.','4'),('Compare y=3x+1 and y=3x-5.','Same rate; first starts 6 units higher'),('A tank has 90 L and drains 6 L/min. Model.','V=90-6t'),('When is tank at 42 L?','8 minutes'),('Does (5,16) lie on y=3x+1?','Yes'),('From y values 8,13,18 as x rises by 1, find rate.','5'),('Write context for y=12x+30.','Answers vary; $30 start plus $12 per unit'),('Explain negative slope in context.','Output decreases as input increases'),('Find equation through (0,-3),(4,5).','y=2x-3'),('State one limitation of a linear model.','Constant rate may not continue outside observed range.')]),
dict(slug='college-french101-cafe',title='French 101 Cafe Conversations',level='College - French 101',state='Not applicable',subject='French',rtype='Independent Work',standard='Course objective - Exchange basic greetings and cafe requests using polite expressions, articles, and present-tense forms of etre and avoir.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed.',price='$6.00',time='35-45 minutes',focus='Use beginner French for greetings, identity, and simple cafe interactions.',qs=[('Translate: Good morning.','Bonjour.'),('Complete: Je ___ etudiante.','suis'),('Complete: Nous ___ deux cafes.','avons'),('Say: I would like a tea, please.','Je voudrais un the, s\'il vous plait.'),('Choose article for croissant: un or une?','un'),('Ask: How are you?','Comment allez-vous ?'),('Reply: I am well, thank you.','Je vais bien, merci.'),('Translate: The bill, please.','L\'addition, s\'il vous plait.'),('Complete: Tu ___ faim.','as'),('Plural of un cafe','des cafes'),('Put in order: voudrais / je / eau / une','Je voudrais une eau.'),('Give a polite closing.','Merci. Au revoir.'),('Write a two-line greeting exchange.','Answers vary; accurate greeting and response.'),('Correct: Je es professeur.','Je suis professeur.'),('Translate: We have a reservation.','Nous avons une reservation.'),('Write a four-line cafe dialogue.','Must include greeting, request, response, and thanks.')]),
dict(slug='college-german101-introductions',title='German 101 Introductions Practice',level='College - German 101',state='Not applicable',subject='German',rtype='Classwork',standard='Course objective - Introduce oneself and exchange basic personal information using greetings, pronouns, sein, heissen, and regular present-tense verbs.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed.',price='$6.00',time='35-45 minutes',focus='Build accurate beginner introductions and short exchanges in German.',qs=[('Translate: Good morning.','Guten Morgen.'),('Complete: Ich ___ Katia.','heisse'),('Complete: Wir ___ Studierende.','sind'),('Ask informally: What is your name?','Wie heisst du?'),('Ask formally: Where are you from?','Woher kommen Sie?'),('Reply: I come from Haiti.','Ich komme aus Haiti.'),('Conjugate lernen for er.','lernt'),('Translate: She speaks German.','Sie spricht Deutsch.'),('Correct: Du ist nett.','Du bist nett.'),('Plural pronoun for they','sie'),('Complete: Ihr ___ hier.','seid'),('Give a polite goodbye.','Auf Wiedersehen.'),('Write a two-line introduction.','Answers vary; greeting and name required.'),('Translate: I study English.','Ich lerne Englisch.'),('Question for place of residence.','Wo wohnst du?'),('Write a four-line partner dialogue.','Must include greeting, two information exchanges, and closing.')]),
dict(slug='college-mandarin101-campus',title='Mandarin 101 Campus Basics',level='College - Mandarin 101',state='Not applicable',subject='Mandarin Chinese',rtype='Task Cards',standard='Course objective - Recognize and use pinyin-supported greetings, names, numbers 1-10, and basic identity questions in short exchanges.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed.',price='$6.00',time='35-45 minutes',focus='Practice respectful beginner exchanges with characters, pinyin, and English meaning.',qs=[('你好 (ni hao) means?','Hello.'),('谢谢 (xiexie) means?','Thank you.'),('你叫什么名字? asks what?','What is your name?'),('Respond: 我叫 Katia.','My name is Katia.'),('Write pinyin for 再见.','zaijian'),('Number 五','5'),('Number 八','8'),('Translate: 我是学生.','I am a student.'),('Which pronoun means I/me? 我 or 你','我 (wo)'),('Which pronoun means you?','你 (ni)'),('Put in order: 叫 / 我 / Leonidas','我叫 Leonidas.'),('Say: Nice to meet you.','很高兴认识你 (hen gaoxing renshi ni).'),('Count 1-5 in pinyin.','yi, er, san, si, wu'),('What does 是 (shi) do in identity sentences?','Links the subject to a noun, similar to "to be."'),('Write a two-line greeting.','Answers vary; accurate greeting and reply.'),('Write a four-line introduction with pinyin support.','Must include greeting, name question/answer, and closing.')]),
dict(slug='college-asl101-classroom',title='ASL 101 Classroom Communication Guide',level='College - ASL 101',state='Not applicable',subject='American Sign Language',rtype='Visual Practice Guide',standard='Course objective - Apply basic visual-attention norms, fingerspell names, and produce beginner greetings and classroom exchanges with appropriate nonmanual signals.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed. Static text descriptions supplement, but do not replace, qualified live or video instruction.',price='$6.00',time='35-45 minutes',focus='Practice respectful visual communication, fingerspelling strategy, and beginner ASL discourse norms.',qs=[('What should you establish before signing?','Visual attention/eye contact.'),('Name one respectful way to gain attention.','Wave within sight, tap shoulder lightly, or use room light with permission.'),('Why is mouthing every English word not ASL grammar?','ASL has its own grammar and nonmanual markers.'),('What is fingerspelling mainly used for?','Names, places, and terms without a known sign.'),('How should beginners fingerspell a name?','Smoothly at readable pace, not letter-by-letter punching.'),('What nonmanual signal commonly marks yes/no questions?','Raised eyebrows with appropriate body posture.'),('What marks many WH-questions?','Furrowed/lowered eyebrows near the question.'),('Where should hands stay for clear signing?','Comfortable signing space visible to partner.'),('Why avoid grabbing a Deaf signer for attention?','It is intrusive; use respectful visual/tactile norms.'),('What is gloss?','A limited written notation for discussing signs, not ASL itself.'),('Plan a greeting sequence.','Attention, greeting, name exchange, closing.'),('How can a partner request repetition?','Use an appropriate repeat/again request and puzzled facial expression.'),('Why does eye gaze matter?','It maintains attention and carries grammatical/social information.'),('Describe an accessible seating arrangement.','Clear sightlines, adequate light, minimal visual obstruction.'),('Self-assess fingerspelling.','Check hand position, rhythm, clarity, and eye gaze.'),('Write a practice plan.','Short repeated practice with feedback from qualified sources.')]),
dict(slug='college-art-composition',title='Art Appreciation Composition Detective',level='College - Art Appreciation',state='Not applicable',subject='Fine Arts',rtype='Analysis Packet',standard='Course objective - Analyze how line, shape, color, value, texture, space, emphasis, balance, rhythm, and unity affect meaning in original compositions.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed. All included geometric studies are original.',price='$7.00',time='45-60 minutes',focus='Use precise art vocabulary to analyze and revise original abstract compositions.',qs=[('Define emphasis.','A focal area given greater visual attention.'),('Define balance.','Distribution of visual weight.'),('How can contrast create emphasis?','A strong difference isolates or highlights an element.'),('Difference between shape and form?','Shape is two-dimensional; form appears or is three-dimensional.'),('What can repeated lines create?','Rhythm or movement.'),('How does value affect depth?','Light-dark shifts can suggest volume and distance.'),('Describe symmetrical balance.','Visual weight mirrors across an axis.'),('Describe asymmetrical balance.','Unequal elements achieve visual equilibrium.'),('What is negative space?','Area around and between subjects.'),('How can warm colors affect focus?','They may appear to advance and attract attention.'),('Choose two elements to show calm.','Answers vary; e.g., horizontal lines and low contrast.'),('Choose two elements to show tension.','Answers vary; e.g., diagonals and sharp contrast.'),('Explain unity.','Parts feel intentionally related as a whole.'),('Revise a crowded composition.','Increase negative space and strengthen hierarchy.'),('Write a three-sentence formal analysis.','Must name evidence and explain effect.'),('Distinguish observation from interpretation.','Observation states visible facts; interpretation explains possible meaning.')]),
dict(slug='college-engineering-design',title='Introduction to Engineering Design Challenge',level='College - Introductory Engineering',state='Not applicable',subject='Engineering / CTE',rtype='Project Packet',standard='Course objective - Define a design problem, distinguish criteria from constraints, generate and compare concepts, plan a fair test, and justify an evidence-based iteration.',source='Course-level learning objective; no accreditation, transfer, or universal equivalency claimed.',price='$7.00',time='60-90 minutes',focus='Design a low-cost paper structure that supports a specified load while documenting decisions and test evidence.',qs=[('Define criterion.','A desired feature or measure of success.'),('Define constraint.','A limit the design must obey.'),('Given max 10 sheets, identify the constraint.','Use no more than 10 sheets.'),('Given support 500 g, identify the criterion.','Support at least 500 g.'),('Why generate multiple concepts?','To compare alternatives before committing.'),('Name a fair-test variable to control.','Same load placement, materials, span, or test time.'),('What is a prototype?','A testable representation of a design idea.'),('Why record failure location?','It reveals where and how to improve the design.'),('Create a weighted decision matrix with three criteria.','Answers vary; criteria, weights, scores, totals required.'),('What makes test evidence reliable?','Consistent procedure and repeat trials.'),('Distinguish accuracy from precision.','Accuracy is closeness to true value; precision is repeatability.'),('Suggest one safety rule.','Keep loads low, protect hands/eyes, and clear the test area.'),('How can triangles strengthen structures?','They resist shape change and distribute loads.'),('State a testable claim about folded paper.','Answers vary; must identify design change and measurable outcome.'),('Use evidence to justify an iteration.','Cite test result, failure mode, and planned change.'),('Reflect on tradeoffs.','Explain how improving one criterion may reduce another.')]),
]

styles=getSampleStyleSheet(); navy=colors.HexColor('#17324D'); blue=colors.HexColor('#255AA8'); red=colors.HexColor('#D62828'); gold=colors.HexColor('#F4B942')
styles.add(ParagraphStyle(name='CoverTitle',parent=styles['Title'],fontSize=27,leading=31,textColor=colors.white,alignment=TA_CENTER,spaceAfter=12))
styles.add(ParagraphStyle(name='H',parent=styles['Heading1'],fontSize=18,leading=22,textColor=navy,spaceAfter=9))
styles.add(ParagraphStyle(name='B',parent=styles['BodyText'],fontSize=10.2,leading=14.2,spaceAfter=6))
styles.add(ParagraphStyle(name='Small',parent=styles['BodyText'],fontSize=8.4,leading=11,textColor=colors.HexColor('#45556A')))

def branded(canvas,doc):
    canvas.saveState()
    canvas.drawImage(ImageReader(str(LOGO)),36,730,width=54,height=38,preserveAspectRatio=True,mask='auto')
    canvas.setFont('Helvetica-Bold',7.5); canvas.setFillColor(navy); canvas.drawString(96,749,'SAINT PIERRE LEARNING RESOURCES')
    canvas.setStrokeColor(gold); canvas.line(36,40,576,40)
    canvas.setFont('Helvetica',7.3); canvas.setFillColor(colors.HexColor('#52606D'))
    canvas.drawString(36,27,'© 2026 Saint Pierre Learning Resources • Single-teacher license • Private draft')
    canvas.drawRightString(576,27,f'Page {doc.page}')
    canvas.restoreState()

listings=[]
for p in P:
    path=OUT/(p['slug']+'.pdf')
    doc=SimpleDocTemplate(str(path),pagesize=letter,leftMargin=42,rightMargin=42,topMargin=78,bottomMargin=50)
    s=[]
    cover=Table([[Image(str(LOGO),width=150,height=106)],[Paragraph(p['title'],styles['CoverTitle'])],[Paragraph(f"{p['level']} • {p['subject']}<br/>{p['rtype']}",ParagraphStyle('cv',parent=styles['B'],alignment=TA_CENTER,textColor=colors.white,fontSize=13,leading=18))],[Paragraph('Original Practice • Assessment • Complete Teacher Key',ParagraphStyle('cv2',parent=styles['B'],alignment=TA_CENTER,textColor=colors.white,fontSize=10))]],colWidths=[500],rowHeights=[125,170,75,62])
    cover.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),navy),('BACKGROUND',(0,1),(0,1),blue),('BOX',(0,0),(-1,-1),4,gold),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(0,0),(-1,-1),'CENTER'),('LEFTPADDING',(0,0),(-1,-1),22),('RIGHTPADDING',(0,0),(-1,-1),22)])); s += [cover,PageBreak()]
    s += [Paragraph('Teacher Guide',styles['H']),Paragraph(f"<b>Level:</b> {p['level']}<br/><b>State:</b> {p['state']}<br/><b>Subject:</b> {p['subject']}<br/><b>Resource type:</b> {p['rtype']}<br/><b>Estimated time:</b> {p['time']}",styles['B']),Paragraph(f"<b>Standard / objective:</b> {p['standard']}",styles['B']),Paragraph(f"<b>Source note:</b> {p['source']}",styles['Small']),Paragraph('<b>What is included:</b> branded cover, teacher guide, student directions, 16 original practice items, 5-item exit ticket, complete answer key/worked guidance, differentiation supports, printing notes, and license statement.',styles['B']),Paragraph(f"<b>Purpose:</b> {p['focus']}",styles['B']),Paragraph('<b>Preparation:</b> Print student pages single-sided or assign through a secure LMS. Review the key and select tools allowed for your learners. No special commercial curriculum is required.',styles['B']),Paragraph('Access and differentiation',styles['H']),Paragraph('<b>AIG:</b> require a second representation, proof, counterexample, transfer task, or student-created extension. <b>504:</b> provide extended time, chunked sections, breaks, reduced copying, and accessible digital zoom as specified by the plan. <b>EC:</b> preteach vocabulary, model one item, provide manipulatives/visuals, and accept aligned response modes from the IEP. <b>ESL:</b> preview key terms, provide bilingual resources and sentence frames, and allow partner rehearsal. Use each learner’s current plan; this guide does not replace it.',styles['B']),PageBreak()]
    s += [Paragraph('Student Practice',styles['H']),Paragraph(f"<b>Learning focus:</b> {p['focus']}",styles['B']),Paragraph('Directions: Complete all items. Show calculations, cite evidence, or explain your reasoning when requested. Check your work before submitting.',styles['B'])]
    for i,(q,a) in enumerate(p['qs'][:8],1): s += [Paragraph(f'<b>{i}.</b> {q}',styles['B']),Spacer(1,14)]
    s += [PageBreak(),Paragraph('Student Practice - Continued',styles['H'])]
    for i,(q,a) in enumerate(p['qs'][8:],9): s += [Paragraph(f'<b>{i}.</b> {q}',styles['B']),Spacer(1,14)]
    s += [PageBreak(),Paragraph('Exit Ticket',styles['H']),Paragraph('Complete independently in 8-10 minutes.',styles['B']),Paragraph('1. State the main skill or concept in your own words.',styles['B']),Spacer(1,32),Paragraph('2. Create one accurate example that uses today’s skill.',styles['B']),Spacer(1,38),Paragraph('3. Explain how you checked your example.',styles['B']),Spacer(1,38),Paragraph('4. Identify one common error and correct it.',styles['B']),Spacer(1,38),Paragraph('5. Rate your confidence from 1-4 and name your next practice step.',styles['B']),Spacer(1,32),Paragraph('<b>Quick rubric:</b> 4 = accurate, complete, and well justified; 3 = accurate with minor omission; 2 = partial understanding; 1 = limited evidence; 0 = blank or unrelated.',styles['B']),PageBreak(),Paragraph('Complete Teacher Answer Key',styles['H'])]
    for i,(q,a) in enumerate(p['qs'],1): s += [Paragraph(f'<b>{i}.</b> {a}',styles['B'])]
    s += [Spacer(1,8),Paragraph('<b>Exit ticket guidance:</b> Responses vary. Award full credit when the student accurately explains the focus, supplies a correct example, describes a valid check, identifies and corrects a realistic misconception, and chooses a specific next step.',styles['B']),Paragraph('<b>Verification:</b> Fixed responses and calculations were checked during production. Open responses are evaluated against the criteria above.',styles['B']),Paragraph('<b>Originality and use:</b> This packet contains original educational content. It does not reproduce released-test items or branded curriculum. One purchaser may use it with their own students; redistribution, resale, and public posting are not permitted.',styles['Small'])]
    doc.build(s,onFirstPage=branded,onLaterPages=branded)
    listings.append({**{k:p[k] for k in ['slug','title','level','state','subject','rtype','standard','price','time']},'status':'private draft - not approved for sale','formats':['PDF'],'pages':6,'private_file':f"output/private-drafts/2026-09-14/{p['slug']}.pdf",'private_thumbnail':f"output/private-thumbnails/2026-09-14/{p['slug']}.png",'summary':p['focus'],'description':f"A complete {p['rtype'].lower()} resource designed to help learners {p['focus'].lower()} Includes teacher guidance, substantial original practice, an exit ticket, a complete key, and learner-access supports.",'whats_included':['1 branded cover','1 teacher guide','16 original practice items','1 five-item exit ticket','1 complete answer key','AIG/504/EC/ESL guidance','printing and single-teacher license notes'],'student_directions':'Complete every item; show work or cite evidence; check work before submitting.','teacher_use':'Use for instruction, guided practice, independent practice, reteaching, enrichment, or formative assessment.','answer_key':'Complete fixed-response key plus criteria for open responses and exit ticket.','accessibility':'AIG extensions; 504 pacing and format options; EC modeling and response supports; ESL vocabulary, bilingual-resource, and rehearsal supports.','prep':'Print single-sided or assign in a secure LMS; review key and permitted tools.','digital_printing':'US Letter PDF; suitable for print or secure digital annotation.','license':'Single-teacher classroom license; no redistribution, resale, or public posting.','originality':'Original content; no released-test items or branded curriculum reproduced.','tags':[p['subject'],p['rtype'],p['level'],p['state'],'answer key','differentiation'],'thumbnail_alt':f"Cover of {p['title']} by Saint Pierre Learning Resources with KSP Haitian-flag logo."})

(ROOT/'data/private-drafts-2026-09-14.json').write_text(json.dumps(listings,indent=2,ensure_ascii=False))
tracker=json.loads((ROOT/'data/product-tracker.json').read_text())
tracker['last_updated']='2026-09-14'
new_titles={p['title'] for p in P}
tracker['completed']=[item for item in tracker['completed'] if item.get('title') not in new_titles]
tracker['completed'].extend([{('standard' if p['state']!='Not applicable' else 'objective'):p['standard'],'title':p['title'],'state':p['state'],'grade':p['level'],'subject':p['subject'],'resource_type':p['rtype'],'format':'PDF'} for p in P])
(ROOT/'data/product-tracker.json').write_text(json.dumps(tracker,indent=2,ensure_ascii=False))
print(f'created {len(P)} private draft PDFs and listings')
